### ISSUE TITLE
کند بودن پارسر وابستگی

### ISSUE THREAD

**Issue by zeinabm** [sobhe/hazm#100]
سلام
من قصد دارم از تعداد زیادی جمله تجزیه وابستگی به دست بیارم و مطابق فرمتی که در ویکی بیان شده، پیش می‌رم ولی بسیار کند هست. آیا راهی هست که سرعت تجزیه‌گر وابستگی افزایش پیدا کنه؟

**Comment by nournia** [comment]
سلام
لطفا برای سریع شدن پردازش، جمله‌ها رو به صورت دسته‌ای تحلیل کنید.


     parser.parse_sents(sentences)
