### ISSUE TITLE
هضم و نسخه های پایتون

### ISSUE THREAD

**Issue by sajaddp** [sobhe/hazm#101]
سلام
وقت بخیر.
آیا هضم با نسخه 3.6.2 می تونه کار کنه؟
دلیل سوال بنده این هست که ظاهرا مدت هاست صفحه ی زیر بروزرسانی نشده:
https://pypi.python.org/pypi/hazm/0.5

**Comment by nournia** [comment]
<div dir=rtl>

سلام
بله، نسخه پایتون ۳.۶ رو به تست‌های پایتون اضافه کردم و همه چیز مرتبه.

مدتی هست که توسعه دادیم ولی ریلیز نکردیم، تا ریلیز جدید می‌تونید از نسخه در حال توسعه استفاده کنید.
