### ISSUE TITLE
POS tagger tagsets

### ISSUE THREAD

**Issue by azarezade** [sobhe/hazm#103]
چطور می‌توان لیست تگ‌های استفاده شده و اینکه هر کدام چیست را دید؟

**Comment by nournia** [comment]
<div dir=rtl>

لطفا اینجا رو ببینید: #58

**Comment by maryammansori** [comment]
ربط داشت اینجا سوالمو پرسیدم  pos_tagسلام من سوالم چون به
 ذخیره میکنم  utf8  من ازهضم برای برنامه ام استفاده میکنم و داخل برنامه ام فایل خروجیم را با 
 ولی وقتی فایل خروجی را میبینم همه قسمتها(ریشه یابی وغیره)فارسی نوشته شدن ولی خروجی 
به صورت زیر است:pos_tag
            (u'\u0645\u0644\u062a', u'Ne');	            (u'\u0628\u0632\u0631\u06af', u'AJe');	            (u'\u0627\u06cc\u0631\u0627\u0646', u'N');	            (u'\u060c', u'PUNC');	            (u'\u067e\u06cc\u0631\u0648\u0632', u'AJe');	            (u'#\u0627\u0646\u062a\u062e\u0627\u0628\u0627\u062a', u'Ne');	            (u'\u0634\u0645\u0627\u06cc\u06cc\u062f', u'V');	            (u'\u061b', u'PUNC');	            (u'\u062e\u0627\u0636\u0639\u0627\u0646\u0647', u'ADV');	            (u'\u062f\u0631', u'P');	            (u'\u0628\u0631\u0627\u0628\u0631', u'Ne');	            (u'\u0634\u0645\u0627', u'PRO');	            (u'\u0633\u0631', u'Ne');	            (u'\u062a\u0639\u0638\u06cc\u0645', u'N');	            (u'\u0641\u0631\u0648\u062f', u'N');	            (u'\u0645\u06cc\u200c\u0622\u0648\u0631\u0645', u'V');	            (u'.', u'PUNC');	

سرچ کردم ولی راه حلی برای نمایش درست پیدا نکردم ممنون میشم راهنمایی بفرمایید ضمن این که من از هضم 4 استفاده میکنم.
