### ISSUE TITLE
 و نصب ورژن 5.0.3 nltk حذف ورژن جدید 

### ISSUE THREAD

**Issue by MahdiDoost** [sobhe/hazm#106]
بسم الله الرحمن الرحیم
با سلام
nltk 5.2.3 بنده با ورژن
کار می کنم. با نصب هضم این ورژن حذف و ورژن 5.0.3 جایگزین می شود.
راه کاری برای این موضوع وجود دارد؟
با سپاس فراوان

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا نسخه در حال توسعه هضم رو نصب کنید که با نسخه جدیدتر nltk سازگار هست:

    sudo pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
بابت نسخه جدید سپاسگزارم.
