### ISSUE TITLE
آنالیز احساسات

### ISSUE THREAD

**Issue by barooni69** [sobhe/hazm#107]
سلام وقتتون بخیر
ببخشید شما روی تجزیه و تحلیل احساسات در زبان فارسی هم کار کردید؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
هضم این ابزار رو نداره.
اضافه کردن این ابزار نیازمند داده تحلیل احساسات هست که الان با حجم مناسب و در دسترس عموم‌ش رو برای فارسی نمی‌شناسم.
