### ISSUE TITLE
error "ModuleNotFoundError: No module named 'hazm.Chunker'; 'hazm' is not a package"

### ISSUE THREAD

**Issue by maryammansori** [sobhe/hazm#109]
سلام من برای  پایان نامه ام از ابزار هضم شما میخام استفاده کنم وبه دلیل این که میخام روی ویندوز پایتون را استفاده کنم از هضم نسخه 4 استفاده میکنم ولی موقع اجرای کد با خطای زیر مواجه میشوم من
 را هم نصب کردم ولی خطاها پابرجاست NLTKو JDK 
من سایتتون هم برای نصب هضم را دیدم و کارهایی رو که گفته بودید انجام دادم
.ممنون میشم راهنمایی بفرمایید 

Traceback (most recent call last):
  File "C:/Users/.../HazmTest.py", line 8, in <module>
    from hazm import *
  File "C:\Users\...\hazm.py", line 10, in <module>
    from hazm.Chunker import tree2brackets
ModuleNotFoundError: No module named 'hazm.Chunker'; 'hazm' is not a package

**Comment by nournia** [comment]
<div dir=rtl>

سلام
بخشی که برای نصب هضم روی ویندوز آورده شده رو دیدید؟

**Comment by maryammansori** [comment]
سلام ممنون از لطفتون
مشکلی که داشت یه فایل پایتون  دیگه کنارفایلی که کد هضمم نوشته بودم قرار
داشت که اون فایل  را که حذف کردم کدم اجرا شد وخودمم کلی تعجب کردم اخه اصلا
اون فایل ربطی به این فایل که کد هضم داخلش بود نداشت.

**Comment by nournia** [comment]
<div dir=rtl>

موفق باشید.
