### ISSUE TITLE
hazm-0.5.3 & stopwords

### ISSUE THREAD

**Issue by MahdiDoost** [sobhe/hazm#110]
بسم الله الرحمن الرحیم
با سلام
بنده نسخه جدید هضم رو نصب کردم ولی خطای زیر رو میده:
from hazm import stopwords
ImportError: cannot import name 'stopwords'
نسخه هضم موجود: Successfully installed hazm-0.5.3
با تشکر فراوان

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا از سورس نصب کنید:

    sudo pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
ممنون از پاسختون
متاسفانه حل نشد.
`ImportError: cannot import name 'stopwords'
`

**Comment by nournia** [comment]
<div dir=rtl>

لطفا این‌طوری استفاده کنید:

    from hazm import stopwords_list

این تابع، فهرست واژه‌ها رو برمی‌گردنه.

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام

> 

> 
> لطفا این‌طوری استفاده کنید:
> 
> from hazm import stopwords_list
> 
> این تابع، فهرست واژه‌ها رو برمی‌گردنه

.

نحوه دسترسی به کلمات ایست در این تابع به چه شکل است؟
با سپاس فروان

**Comment by nournia** [comment]
<div dir=rtl>

تابع رو کافیه صدا بزنید. خروجی یک لیست از کلمات هست.
</div>

    stopwords_list()

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
بابت پاسخ بینهایت سپاسگزارم.

**Comment by AlirezaGhafartehrani** [comment]
سلام
برای حذف stop words ها از یک متن چطور میشه اقدام کرد؟

**Comment by pooyaphoenix** [comment]
`from hazm import stopwords_list

text = 'این یک تست برای کلمات ایست در زبان فارسی است'
text = ' '.join([word for word in text.split() if word not in stopwords_list()])
print(text)
`

**Comment by pooyaphoenix** [comment]
`
from hazm import stopwords_list

text = 'این یک تست برای کلمات ایست در زبان فارسی است'
text = ' '.join([word for word in text.split() if word not in stopwords_list()])
print(text)

`

**Comment by pooyaphoenix** [comment]
` from hazm import stopwords_list
text = 'این یک تست برای کلمات ایست در زبان فارسی است'
text = ' '.join([word for word in text.split() if word not in stopwords_list()])
print(text) `

output:
تست کلمات ایست زبان فارسی

**Comment by mhk67** [comment]
برای استفاده کد زیر رو میتونید بررسی کنید:

from hazm import stopwords_list,word_tokenize
sentence= 'این یک تست برای کلمات ایست در زبان فارسی است'
words = word_tokenize(sentence)
words = [word for word in words if not word in stopwords_list()]
print(words)
