### ISSUE TITLE
\u200c & Normalizer

### ISSUE THREAD

**Issue by MahdiDoost** [sobhe/hazm#111]
بسم الله الرحمن الرحیم
با سلام
```
`>>> from hazm import *
>>> normalizer = Normalizer()
>>> normalizer.normalize('همشهری‌آنلاین')
'همشهری\u200cآنلاین'
>>> `
```

چرا عبارت 'همشهری‌آنلاین' را به شکل بالا نرمال می کند؟
با سپاس فراوان

**Comment by barooni69** [comment]
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
 from hazm import *
 normalizer = Normalizer()
 normalizer.normalize('همشهری‌آنلاین')

حالا امتحان کنید

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
متاسفانه درست نشد
```
>>> from __future__ import unicode_literals
>>> from hazm import *
>>> normalizer = Normalizer()
>>> normalizer.normalize('همشهری‌آنلاین')
'همشهری\u200cآنلاین'
```

**Comment by nournia** [comment]
<div dir=rtl>

سلام
اینکه نوشته \u200c مربوط هست به نحوه چاپ شدن متن و این معادل یونیکد کاراکتر نیم‌فاصله هست. 
اگر می‌خواید درست ببینید این کار رو بکنید:

</div>

      >>> print(normalizer.normalize('همشهری‌آنلاین'))

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
بابت پاسخ سپاسگزارم.
