### ISSUE TITLE
word_tokenize In hazm

### ISSUE THREAD

**Issue by MahdiDoost** [sobhe/hazm#113]
بسم الله الرحمن الرحیم
با سلام
```
>>> from __future__ import unicode_literals
>>> from hazm import *
>>> text1 = 'فیلم انگلیسی‌زبان «این جا باید باشد» با بازی شان پن جوایز بهترین فیلمنامه، فیلمبرداری، موسیقی، ترانه، چهره‌پردازی و مو را برد.'
>>> normalizer = Normalizer()
>>> text1=normalizer.normalize(text1)
>>> word_tokenize_list = word_tokenize(text1)
>>> print(len(word_tokenize_list))
28
>>> print(word_tokenize_list)
['فیلم', 'انگلیسی\u200cزبان', '«', 'این', 'جا', 'باید', 'باشد', '»', 'با', 'بازی', 'شان', 'پن', 'جوایز', 'بهترین', 'فیلمنامه', '،', 'فیلمبرداری', '،', 'موسیقی', '،', 'ترانه', '،', 'چهره\u200cپردازی', 'و', 'مو', 'را', 'برد', '.']
>>> 
```
تعداد کلمه های جمله ای که در کد بالا مشخص شده است، ۲۱ کلمه می باشد ولی در کد بالا ۲۸ نشان داده شده است.
چراکه علائمی مثل نقطه و ویرگول و ... را یک کلمه به حساب می آورد.
این یک باگ است یا باید قبل از استفاده از توکنایزر کاری انجام دهیم.
با سپاس فراوان

**Comment by Mahdizade** [comment]
سلام. این علائم هم توکن محسوب میشوند.

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
بابت پاسخ سریع بینهایت سپاسگزارم
راهی وجود دارد که این کلمات بدون این علائم را داشته باشم؟
با تشکر

**Comment by nournia** [comment]
<div dir=rtl>

سلام
همون‌طور که گفتن این علامت‌ها نقش می‌گیرن و اگر نمی‌خواید باید خودتون حذف‌شون کنید.

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
از پاسخ سپاسگزارم
