### ISSUE TITLE
چجوری میتونم کلمه فعلهایی که با ؛می؛ شروع میشوند را یکسان کنم؟

### ISSUE THREAD

**Issue by mrmrn** [sobhe/hazm#115]
با سلام
من چند دقیقه میشه که با هضم اشنا شدم و خیلی عالیه.
من میخواستم فعل هایی مثل `میکنم` و `می کنم` و `می‌کنم` رو با هم یکی کنم. چجوری میتونم این کار رو انجام بدم؟
ممنون

**Comment by nournia** [comment]
<div dir=rtl>

سلام
ابزار Normalizer همین کار رو باید انجام بده.
البته الان `میکنم` رو درست نمی‌کنه ولی فاصله بین `می کنم` رو درست می‌کنه.
