### ISSUE TITLE
resources file for hazm0.4

### ISSUE THREAD

**Issue by roetezadi** [sobhe/hazm#119]
با سلام امکانش هست فایل 
resources
برای نسخه 0.4 رو در اختیارم قرار بدین؟ در این سایت امکان دانلودش نیست
https://pypi.python.org/pypi/hazm/0.4

**Comment by nournia** [comment]
<div dir=rtl>

سلام
بفرمایید:
https://github.com/sobhe/hazm/releases/download/v0.4/resources-0.4.zip

**Comment by roetezadi** [comment]
خیلی ممنون
