### ISSUE TITLE
error installing hazm

### ISSUE THREAD

**Issue by salimmakhdom** [sobhe/hazm#121]
![capture](https://user-images.githubusercontent.com/4199468/38997380-ff5c4216-43f5-11e8-9b07-f87d404557cc.JPG)

**Comment by Rohit8y** [comment]
Obviously this one image is not clear enough to tell the answer to your problem but,
Your path only lists Visual Studio 11 and 12, it wants 14, which is Visual Studio 2015. If you install that, and remember to tick the box for Languages->C++ then it should work.

For installing  Hazm you first need to install python 
and then further using 
**pip install hazm**
to install hazm and if you want to install hazm on Anaconda then you can open the below link
https://stackoverflow.com/questions/48903319/install-hazm-on-anaconda-3

**Comment by nournia** [comment]
Hi,
As mentioned in hazm homepage, best method for installing hazm in windows is using WSL:
https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
Plus, if you install hazm from source code, for some of functionalities you don't need to install libwapiti.
