### ISSUE TITLE
Can i get Proper Nouns from Hazm

### ISSUE THREAD

**Issue by Rohit8y** [sobhe/hazm#122]
Thanks in advance
I want to get proper nouns using HAZM.But i think that's  not possible.
If anyone knows any other POS Tagger for Persian which can give Proper Nouns(NNP) then please leave a comment.

**Comment by nournia** [comment]
Hi,
Hazm uses coarse tagset for POS tagging and specifies proper nouns with N tag. If you want to detect proper nouns you can train your POS tagger which is not so difficult. You only need to call [train_postagger](https://github.com/sobhe/hazm/blob/29ad5b1f13edb54fefa096655bc7a34945274d6d/data.py#L107) function with custom `pos_map` which preserves proper noun tag.

**Comment by nournia** [comment]
Hi,
You only need to call that mentioned function. It doesn't need any expertise. Also, you must provide Peykare corpus which is training data for this function.

**Comment by Rohit8y** [comment]
@nournia  I did the same as you mentioned.
How long does it take to train the model.This is my output screen and it's still running 
![screenshot from 2018-06-05 11 42 35](https://user-images.githubusercontent.com/38680205/40958109-b0bf8ff2-68b5-11e8-8bea-681436167f8d.png)

and i have one more doubt'
If i call the [train_postagger](https://github.com/sobhe/hazm/blob/29ad5b1f13edb54fefa096655bc7a34945274d6d/data.py#L107)
function then i will get the same model as the one available in your library.

If i change the tag set of [coarse_pos_e](https://github.com/sobhe/hazm/blob/29ad5b1f13edb54fefa096655bc7a34945274d6d/hazm/PeykareReader.py) by adding NNP or PROPERN tag whatever you are using for your corpus then can i get proper nouns.

Because if i simply call the function without changing the pos_map then i think i will get same postagger.model without Proper Nouns tag

**Comment by nournia** [comment]
I think training procedure takes less than 5 hours on 4 cpu cores and enough memory. Are you sure that you provided Peykare corpus and set proper input variable?
As you said, you need to change `coarse_pos_e` to maintain Proper Noun tags. There is a tiny sample from Peykare corpus [here](https://github.com/sobhe/hazm/blob/master/corpora/peykare/0001.txt). It seems that you need to keep `PR` tag and map it to something like `PN` and `PNe` which shows Proper Noun and Proper Noun with Ezafe.

**Comment by Rohit8y** [comment]
The tiny sample you mentioned of PeyKare corpus do i need to train the model on this small corpus or i have to download the original corpus from somewhere else.
AND
The PR tag that you mentioned what does it stand for Pronoun or Proper Noun and if it stands for Proper Noun then yes extracting PR is my main motive.
And if it stands for Proper noun then do i have to change the tags in this function?
**def coarse_pos_e(tags):**
	try:
		return list(set(tags) & {'N',**'PR**' 'V', 'AJ', 'ADV', 'PRO', 'DET', 'P', 'POSTP', 'NUM', 'CONJ', 'PUNC', 'CL', 'INT', 'RES'})[0] + ('e' if 'EZ' in tags else '')
	except:
		return 'N'

**Comment by nournia** [comment]
That tiny sample only helps you for making your code works. But for training pos tagger you need to request for Peykare corpus. I believe that authors of its paper can help you:

    Bijankhan, M., Sheykhzadegan, J., Bahrani, M., & Ghayoomi, M. (2011). Lessons from building a Persian written corpus: Peykare. Language Resources and Evaluation, 45, 143–164

Pronoun tag is specified with `PRO` identifier and I didn't find Proper Noun tag identifier in Peykare paper.

**Comment by nournia** [comment]
You can find first author's email in his [homepage](https://rtis2.ut.ac.ir/cv/mbjkhan/?lang=en-gb).
I'm not sure about Peykare license and I don't know if it permits that.
