### ISSUE TITLE
دادگان آموزش برای برچسب زنی 

### ISSUE THREAD

**Issue by hadifar** [sobhe/hazm#124]
از چه دادگانی برای آموزش برچسب زنی نحوی استفاده شده است؟ آیا این دادگان به صورت آزاد دسترس هستند؟ اگر آره امکانش هست لینکشو رو بدید.

با تشکر

**Comment by nournia** [comment]
<div dir=rtl>

سلام
از مجموعه داده درخت وابستگی که می‌تونید اینجا پیداش کنید:
http://dadegan.ir/catalog/perdt/about
