### ISSUE TITLE
I got error during installaion  c1083

### ISSUE THREAD

**Issue by hossein890** [sobhe/hazm#126]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icwapiti/src -Ilibwapiti -Ic:\users\hossein\appdata\local\programs\python\python36-32\include -Ic:\users\hossein\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tccwapiti/src/bcd.c /Fobuild\temp.win32-3.6\Release\cwapiti/src/bcd.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    bcd.c
    c:\users\hossein\appdata\local\temp\pip-build-qa2j2z0c\libwapiti\cwapiti\src\model.h(33): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\hossein\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hossein\\AppData\\Local\\Temp\\pip-build-qa2j2z0c\\libwapiti\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Hossein\AppData\Local\Temp\pip-dm2rksji-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Hossein\AppData\Local\Temp\pip-build-qa2j2z0c\libwapiti\
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

>

**Comment by theAmouie** [comment]
Nobody solved this problem yet?

**Comment by nournia** [comment]
<div dir=rtl>

سلام
همون‌طور که در صفحه اول هضم نوشته شده برای نصب روی ویندوز می‌تونید از ویژگی WSL ویندوز استفاده کنید.
اگر می‌خواید حتما در ویندوز کامپایل کنید، باید بگم که سخت هست ولی با Cygwin ممکنه.
