### ISSUE TITLE
Type Persian in Python

### ISSUE THREAD

**Issue by puraminy** [sobhe/hazm#13]
Thank you for your great work
I read your examples in the ReadMe 
you have used Persian sentences in Persian alphabets,
but I couldn't type persian in python console
which software, shell or settings you used to type in Persian?

**Comment by aliasgaras** [comment]
سلام من یه مشکلی دارم میخوام متن فارسی رو به چسبونم گوشه صفحه برای مثال
http://uupload.ir/files/rdwt_untitled.png
این طوری بشه

**Comment by aliasgaras** [comment]
اگه بتونید کمک کنید ممنون میشم

**Comment by ThePokerFaCcCe** [comment]
سلام من یه مشکلی دارم که شاید خیلیی به این پست مربوط نشه اما جایی روپیدا نکردم که مشکلمو حل کنه..
من برای نوشتن در فایلها به زبان فارسی ب مشکل بر میخورم . ی مثال سادش اینه:
f.write('سلام')
که اروری مثل این میده:
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-13: character maps to <undefined>

**Comment by khaled-dev-loper** [comment]
اگر میخواهید از محیط CMD استفاده کنید
یا همون خط فرمان ویندوز 

به لینک زیر مراجعه کنید
[کلیک کنید](https://www.aparat.com/v/Ft950)

یک ویدیو آموزشی هست که به شما نشان میدهد چگونه در خط فرمان ویندوز ، فارسی بنویسید
