### ISSUE TITLE
درست کار نکردن یک دستور در هضم

### ISSUE THREAD

**Issue by attar110** [sobhe/hazm#133]
با سلام
هضم رو نصب کردم همه قسمتهاش کارمی کنه اما دستورات زیر خروجیش غلطه و مطابق مستدات شما نیست لطفا راهنمایی بفرمایید/
lemmatizer = Lemmatizer()
lemmatizer.lemmatize('میروم')
'میروم'

**Comment by nournia** [comment]
<div dir=rtl>

سلام
متاسفانه در حال حاضر نسخه متن‌باز هضم نمی‌تونه واژه «میروم» رو اصلاح بکنه.
ولی در صفحه دمو هضم، بخشی هست که این واژه رو به «می‌روم» تبدیل می‌کنه و بعد می‌تونید ریشه‌یابی‌ش کنید.
البته ابزار اصلاح متنی که گفتم رو متن‌باز نکردیم.

**Comment by kokabi1365** [comment]
<div dir="rtl">
در نسخه‌های جدید این مشکل حل شده.
</div>
