### ISSUE TITLE
مشکل در توکنایز کلماتی که ان در انتها دارند

### ISSUE THREAD

**Issue by reza1615** [sobhe/hazm#134]
بعد از 
tokeniz
برای کلماتی مانند «قربان» آنها را به «قرب» تبدیل می‌کند که بی‌معنی‌ست
http://www.boute.ir/iust-ai-92/keyword-extraction

**Comment by reza1615** [comment]
فهرستی از لغاتی که با ان خاتمه می‌یابند تهیه کردم که اگر بشود آنها را در فهرست سیاه توکنایز قرار داد به نظرم این مشکل رفع شود.
[words with an.txt](https://github.com/sobhe/hazm/files/2281712/words.with.an.txt)

**Comment by nournia** [comment]
<div dir=rtl>

سلام
ابزار Tokenizer فقط وظیفه جدا کردن واژه‌ها رو داره. به نظرم منظور شما ابزار Stemmer هست.
همون‌طور که گفتید Stemmer واژه قربان رو به قرب تبدیل می‌کنه. دلیل‌ش این هست که ابزار کلا هوش نداره و به واژه‌ها توجه نمی‌کنه. اگر نمونه‌های انگلیسی رو هم ببینید، دقیقا با همین مشکل مواجه هستن.
ابزاری که باید در واقع استفاده بشه Lemmatizer هست که ریشه واژه‌ها رو مشخص می‌کنه و این اشتباهی که نوشتید رو هم مرتکب نمی‌شه.
