### ISSUE TITLE
مشکل در بردازش در بخش stemmer

### ISSUE THREAD

**Issue by Nazifa12** [sobhe/hazm#136]
چه کار کنیم تا stemmer
ما کلمات تکراری را برای نکشد؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
می‌تونید با مثال توضیح بدید؟
استمر واژه‌ها رو باید ساده بکنه.  مثلا کتاب‌ها رو باید بکنه کتاب.

**Comment by nournia** [comment]
<div dir=rtl>

لطفا اینجا رو هم ببینید #137
