### ISSUE TITLE
برچسب گذاری معنایی

### ISSUE THREAD

**Issue by barooni69** [sobhe/hazm#138]
سلام و درود

آیا در هضم از برچسب گذاری معنایی استفاده می شود؟ و اگر موجود است لطفا طرز استفاده از آن را ذکر کنید و اگر وجود ندارد آیا در زبان فارسی ابزاری برای برچسب گذاری معنایی متون وجود دارد؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
متاسفانه هضم ابزار برچسب‌گذاری معنایی نداره.
البته چند وقتی هست که داده فارسی برای این موضوع منتشر شده، می‌تونید روی اون داده مدلی رو آموزش بدید.

**Comment by kokabi1365** [comment]
Duplicate of #97
