### ISSUE TITLE
Do you maintain repository?

### ISSUE THREAD

**Issue by hadifar** [sobhe/hazm#139]
Hi Hazm team,
Currently I not seeing any update in the repository. Do you have plan to maintain the repository?  Its good idea to define a set of TODO task  in readme for those who are interested for collaborating to the project.

**Comment by nournia** [comment]
<div dir=rtl>

سلام
به نظر من مهم‌ترین بخش‌ها برای توسعه در هضم اینها هستن:
+ بردارهای توصیف واژه‌ای برای استفاده در شبکه‌های عمیق
+ مدل‌های شبکه عمیق برای تحلیل صرفی و تجزیه نحوی
+ تحلیل ساختار واژه‌ها (مورفولوژی)
+ تحیلی متون محاوره
+ مدل زبانی برای فارسی
+ تحلیل زبان عربی
+ ...

در واقع فهرست‌ش طولانی هست. برای بعضی از این کارها ما اقداماتی رو انجام دادیم و امیدواریم در آینده بتونیم بیشتر روی توسعه هضم زمان بذاریم.
