### ISSUE TITLE
comp and sup adjective tags

### ISSUE THREAD

**Issue by mahsaSH717** [sobhe/hazm#143]
با سلام 
آیا در هضم برای صفات مقایسه ای و برتر تگ های خاص در نظر گرفته میشه؟ و میتوان آن ها را از صفات عادی تمیز داد یا خیر؟ اگر بله به چه صورت؟ چون در تست هایی که من  گرفتم این صفات به صورت صفت عادی تگ میگیرند

**Comment by nournia** [comment]
<div dir=rtl>

سلام
ابزار هضم روی تگ‌های درشت مجموعه داده Peykare آموزش دیده و نمی‌تونه نوع صفت رو مشخص بکنه.
اگر می‌خواید این کار رو انجام بدید باید داده‌ها رو از تهیه‌کنندگان‌ش بگیرید و بعد هضم رو آموزش بدید تا نوع صفت رو مشخص بکنه.
راه دیگه هم اینه که سعی کنید با چند قاعده و فهرست واژه این کار رو انجام بدید.
موفق باشید.
