### ISSUE TITLE
خطای TypeError: __init__() got an unexpected keyword argument 'model'

### ISSUE THREAD

**Issue by zohreh3906** [sobhe/hazm#147]
سلام. من درکد زیر 
ormalizer = Normalizer()
    sentence = normalizer.normalize(sentence)
    sentence = re.sub(r'[^\w\s\u200c]', '', sentence)
    words = word_tokenize(sentence)
    #words = remove_stop_words(words)
    tagger = POSTagger(model='resources/postagger.model')
    tags = tagger.tag(words)
 به خطای زیر مواجه شدم. علت چیست؟ فولدر ریسورس هم در جای خود قرار دادم
<ipython-input-19-3be6a531b974> in extract_synsets(sentence)
     11     words = word_tokenize(sentence)
     12     #words = remove_stop_words(words)
---> 13     tagger = POSTagger(model='resources/postagger.model')
     14     tags = tagger.tag(words)
     15     candid_syns = {}

C:\ProgramData\Anaconda3\lib\site-packages\hazm\POSTagger.py in __init__(self, *args, **kwargs)
     14 
     15                 self._SEPARATOR = '/'
---> 16                 super(stanford.POSTagger, self).__init__(*args, **kwargs)
     17 
     18         def tag_sents(self, sentences):

TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by nournia** [comment]
<div dir=rtl>

سلام
به نظر می‌رسه دارید از نسخه قدیمی هضم استفاده می‌کنید. نحوه استفاده از کد قدیمی فکر کنم شبیه به این باشه:
</div>

     tagger = POSTagger(model_filename='resources/persian.tagger', path_to_jar='resources/stanford-postagger.jar')
