### ISSUE TITLE
Meaning of the columns in words.dat

### ISSUE THREAD

**Issue by miracle2k** [sobhe/hazm#154]
Is there more information about what does mean?

My best guess:

- The number is some kind of "word frequency" count.
- N=Noun
- PL=Plural
- RES=...?

**Comment by nournia** [comment]
Hi,
These word tags are based on `Peykare` corpus. You can find more details in its paper:

    Bijankhan, M., Sheykhzadegan, J., Bahrani, M. and Ghayoomi, M., 2011. Lessons from building a Persian written corpus: Peykare. Language resources and evaluation, 45(2), pp.143-164.
