### ISSUE TITLE
یافتن کلمات مشابه

### ISSUE THREAD

**Issue by DeeeepNet** [sobhe/hazm#156]
سلام
1. چجوری میشه کلمات مشابه یک کلمه را پیدا کرد مثلا 10 کلمه مشابه هم
2. اندازه دیکشنری بکارفته چندتا هست
3.آیا قابلیت سرچ روی متون هم دارد یعنی براساس کلمات

**Comment by nournia** [comment]
<div dir=rtl>

سلام
۱. در حال حاضر ویژگی کلمات مشابه در هضم وجود نداره.
۲. یک مجموعه لغات هست در ابزار هضم با اندزه تقریبا ۳۵ هزار واژه. البته باید فعل‌ها رو هم در نظر گرفت که در زمان صرف می‌شن و نمی‌دونم چند تا هستن.
۳. ابزار هضم می‌تونه برای پیش‌پردازش جهت جستجو استفاده بشه ولی خودش امکان سرچ نداره.

موفق باشید.

**Comment by Fazel94** [comment]
یک راه برای پیدا کردن کلمات مشابه استفاده از مدل 
word2vec 
اموزش داده شده روی داده‌گان فارسی هست 
همچین مدلی را می‌توانید از [اینجا](http://dml.qom.ac.ir/2017/02/08/%D9%85%D8%AF%D9%84-%D8%A8%D8%B1%D8%AF%D8%A7%D8%B1%DB%8C-%DA%A9%D9%84%D9%85%D8%A7%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7/) دریافت کنید

برای خواندن مدل از پکیج 
gensim 
استفاده کنید که تابعی به نام
 most_similar 
دارد و دقیق مشکل شما را حل می‌کند
