### ISSUE TITLE
ModuleNotFoundError: No module named 'hazm'

### ISSUE THREAD

**Issue by ali110-star** [sobhe/hazm#160]
سلام من میخواهم از ابزار هضم روی ویندوز استفاده کنم ولی موقع اجرای کد با خطای زیر مواجه میشوم
ModuleNotFoundError: No module named 'hazm'

**Comment by MohammadFakhreddin** [comment]
Hi 
Make sure to run pip3 install hazm in your directory maybe it is installed in wrong directory
Another thing to mention is to use python3 (Avoid using python2)
I used it in my project,I must really thank you guys for creating this awesome library, It helped me a-lot
[https://github.com/MohammadFakhreddin/forum-search-engine](url)
