### ISSUE TITLE
how to find best way to extract text from persian pdfs?

### ISSUE THREAD

**Issue by mbutler-79** [sobhe/hazm#161]
Do you know how can I extract text from pdfs in persian language?
I worked with textract , pdfminer, pdftotext libraries, but none of them was successful.
do you have any idea to solve this problem?

Thanks a lot

**Comment by nournia** [comment]
Hi,
Persian PDF files are generated with various PDF generator softwares and each software uses different algorithm for rendering PDF file.
I think best solution for extracting text from PDF file is using OCR. Please checkout [Alefba](http://sobhe.ir/alefba) which is a robust Persian OCR.
