### ISSUE TITLE
Error in sentence tokenization

### ISSUE THREAD

**Issue by Keramatfar** [sobhe/hazm#163]
Thanks for your great package,
Consider the following example:
`text = 'این یک آزمایش است. این نیز. و این.واین یکی'`

`hazm.sent_tokenize(text)`

You get this:
`['این یک آزمایش است.', 'این نیز.', 'و این.واین یکی']`

Is not better to change the following line:

`pattern = re.compile(r'([!\.\?⸮؟]+)[ \n]+')`

to:

`pattern = re.compile(r'([!\.\?⸮؟]+)')`

The result will be:

`['این یک آزمایش است.', 'این نیز.', 'و این.', 'واین یکی']
`

**Comment by nournia** [comment]
Hi,
There are multiple use cases for `dot` character which I think doesn't indicate sentence boundary. For example in numbers like `1.5` you can't use this simple regex. Your pattern splits every punctuation without seeing its context.
Thanks.
