### ISSUE TITLE
تشخیص موجودیت های نامدار

### ISSUE THREAD

**Issue by zohreh3906** [sobhe/hazm#164]
سلام. آیا در هضم امکان تشخیص موجودیت های نامدار وجود دارد؟
اگر وجود دارد کد آن را قرار دهید و گرنه راهنمایی بفرمایید چه کاری می توان انجام داد.

**Comment by nournia** [comment]
<div dir=rtl>

سلام
در حال حاضر این امکان در هضم وجود نداره.
برای این کار لازم هست کلاس IOBTagger رو با داده تشخیص موجودیت‌های نامدار آموزش بدید.

**Comment by kokabi1365** [comment]
Duplicate of #59
