### ISSUE TITLE
دسترسی به داده های آموزش

### ISSUE THREAD

**Issue by sadeghzahedi** [sobhe/hazm#165]
با سلام و وقت به خیر
آیا امکان دسترسی به داده های آموزش مدل چانکر فراهم است ؟
با تشکر

**Comment by nournia** [comment]
<div dir=rtl>

سلام
کد آموزش مدل چانکر رو [اینجا](https://github.com/sobhe/hazm/blob/9e153ab5b106a872d7d5bd4e7ef0216c20523e23/data.py#L149) می‌تونید ببینید. این کد از داده‌های درخت نحوی استفاده می‌کنه که قابل دریافت هست.
