### ISSUE TITLE
Incorrect wapiti requirement

### ISSUE THREAD

**Issue by mahmoud** [sobhe/hazm#166]
Salam @sobhe! I wanted to point out that in your `setup.py` there seems to be an erroneous reference to `wapiti` instead of `libwapiti`. The former is a library I maintain for talking to Wikipedia APIs, nothing to do with language parsing/tokenization. You may want to adjust this, as some people are [failing to install hazm](https://github.com/mahmoud/wapiti/issues/30) because I haven't ported wapiti to Python 3 yet.

**Comment by nournia** [comment]
Salam Mahmoud,
In [setup.py](https://github.com/sobhe/hazm/blob/master/setup.py) file, we clearly mentioned `libwapiti>=0.2.1` requirement and all of our test cases are passing correctly in Python 3:
https://travis-ci.org/sobhe/hazm

Lots of Iranian developers try to install hazm on Windows machines. But libwapiti could not be compiled easily on Windows.

Hazm community would be grateful of you if you could compile libwapiti `whl` files for windows and linux.

Thanks a lot.

**Comment by mahmoud** [comment]
Hmm that's true, I see that now. I think maybe there was just a misunderstanding on the part of one of your prospective users in the issue linked above. Thanks in any case!
