### ISSUE TITLE
برچسب زنی کامنت

### ISSUE THREAD

**Issue by cnarvd** [sobhe/hazm#168]
سلام و وقت بخیر.دوستان میخواستم ببینم بهترین روش  برای برچسب زنی کامنت ها(راضی-ناراضی-خنثی) با استفاده از هضم چی هست؟

**Comment by Fazel94** [comment]
بهترین که جای بحث داره  ولی راه خیلی خوب، دم دست و مورد استفاده به این شکل هست که :
- متن رو نرمال سازی کنی(با هزم)
- به توکن تبدیل کنی ( با هزم)
- توکن ها رو به فیچر تبدیل کنی (با scikit-learn) 
- فیچر ها رو با روش های مختلف دسته بندی کنی مثلا naive bayes )با scikit-learn)
برای سه مرحله‌ی اول از قطعه کد زیر استفاده می‌کنم.

```python
from sklearn.feature_extraction.text import TfidVectorizer
normalizer = hazm.Normalizer()
tfidf = TfidfVectorizer(lowercase=False, preprocessor=normalizer.normalize, tokenizer=hazm.work_tokenize)
X = tfidf.fit_transform(texts)
```
حالا از X به عنوان ورودی به الگوریتم یادگیری می‌تونی استفاده کنی

**Comment by cnarvd** [comment]
. سپاسگذارم.مراحل پیش پردازش رو طی کردم.بیشتر مشکلم برای قسمت کلاستر کردن هست
این نایو بیز که گفتین برای کلاسیفایینگ قبلا استفاده کرده بودم.برای کلاسترینگ هم میشه ازش استفاده کرد؟

**Comment by csarami** [comment]
https://fa.wikipedia.org/wiki/%D8%AE%D9%88%D8%B4%D9%87%E2%80%8C%D8%A8%D9%86%D8%AF%DB%8C

 از پرکاربردترین ها هستن٬k-means, hierarchical clustering
