### ISSUE TITLE
مشکل در خروجی گرفتن از postagger

### ISSUE THREAD

**Issue by mahmoudtavallaei** [sobhe/hazm#170]
وقتی می خوام از postagger  خروجی بگیرم باخطا مواجه میشم میشه لطفا راهنمایی کنید
با wsl  کار می کنم .

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا بفرمایید که چه خطایی اتفاق می‌افته.

**Comment by MehdiMoosavi88** [comment]
سلام
منم نمی تونم از posttagger خروجی بگیرم و با همچین خطایی روبرو می شم
لطفا راهنمایی کنید
ممنون
![Capture](https://user-images.githubusercontent.com/60131513/72789339-d8277d80-3c48-11ea-864f-0dff129a710b.JPG)

**Comment by nournia** [comment]
<div dir=rtl> 

سلام
همون‌طور که در صفحه اول سایت گفته شده باید از ویژگی WSL ویندوز برای نصب استفاده کنید.
