### ISSUE TITLE
خطا در sequenceTagger

### ISSUE THREAD

**Issue by MehdiMoosavi88** [sobhe/hazm#174]
سلام
من از کتابخانه هضم برای پردازش متن استفاده کردم ولی موقع اجرا با خطای زیر مواجه شدم.
لطفا راهنمایی کنید
ممنون
![Capture](https://user-images.githubusercontent.com/60131513/72803788-226a2800-3c64-11ea-87ec-6da83a9a8b39.JPG)

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا راهنمای نصب در ویندوز رو نگاه کنید.
