### ISSUE TITLE
ریشه‌یابی زبان محاوره‌ای

### ISSUE THREAD

**Issue by yassersouri** [sobhe/hazm#18]
سلام

تا جایی که من تست کردم که لماتایزر نمی‌تونی کلمات محاوره‌ای مثل موارد زیر رو درست ریشه‌یابی کنه:
`
می‌گم. می‌شم. می‌رم.
`

از اونجایی که مسئله از دید مثل منی که خیلی سر در نمیارم از این موضوع ساده به نظر میاد و اینکه خیلی هم مهم هستش آیا راهی نداره که قوانین ریشه‌یابی کنونی رو برای این متون هم گسترش بدید؟

اگر در مورد اهمیتش شک دارید می‌شه گفتگو کرد.

**Comment by rasoolims** [comment]
سلام
اون مثال‌هایی که زده شده برای زبان محاوره‌ای هستند که کاملاً متفاوت با زبان معیار هست و قواعد جداگانه‌ای داره. اولاً انجام همچون کاری خودش نیاز به همت جداگانه‌ای داره و ثانیاً باید یک ابزار روی ابزار داشته باشید که اول تشخیص نوع زبان (محاوره یا معیار)‌کنه بعد با توجه به نوع زبان بیاد ریشه‌یابی رو انجام بده

**Comment by yassersouri** [comment]
@rasoolims حرف من اینه که با توجه به اهمیتی که این موضوع داره آیا سرمایه گذاری روی اون شایسته نیست؟

**Comment by rasoolims** [comment]
توی این بخش کمبود دادهٔ زبانی وجود داره. سرمایه‌گذاری خوب هست ولی خیلی بیشتر از زبان معیار هزینه‌بر و وقت‌گیر می‌تونه باشه. 
به نظرم کاملاً بستگی به هدف مورد استفاده داره. اگر قراره متن‌های خبری یا امثال اون رو بررسی کنید به نظرم اهمیت زیادی نداره ولی اگر محیط وبلاگی یا چت مورد نظرتون باشه، خیلی میتونه مفید باشه

**Comment by yassersouri** [comment]
@rasoolims وقتی که قرار هر بر اساس قواعد ریشه‌یابی انجام بشه، دیگه فکر نکنم که داده زیاد مهم باشه.

مشکلی که من دارم اینه که در حالت کنونی هیچ استفاده‌ای نمی‌تونم بکنم از هضم. یعنی هضم فقط به درد بررسی متن‌های خبری می‌خوره که اون هم به نظر من نسبت به داده‌های موجود در شبکه‌های اجتماعی که بیشتر به شکل محاوره‌ای هستند ارزش و کاربرد خیلی کمتری دارند، حداقل برای من.

البته به درد متون کتاب‌ها هم می‌خوره که البته چنین متونی به سادگی در دسترس نیست.

**Comment by yassersouri** [comment]
@rasoolims یه چند تا مسئله توی حرف‌های شما بود که خواستم بیشتر اطلاع کسب کنم به همین خاطر می‌پرسم:

«برای زبان محاوره‌ای هستند که کاملاً متفاوت با زبان معیار هست»
این کاملاً متفاوت که گفتید یعنی چقدر؟ مثلا اگر زبان فارسی معیار با فارسی محاوره‌ای کاملاً متفاوت هستند، نسبت زبان فارسی معیار با زبان مثلاً لری یا انگلیسی چیه؟ منظورم برای مسئله‌ی ریشه‌یابی ه.

«باید یک ابزار روی ابزار داشته باشید که اول تشخیص نوع زبان (محاوره یا معیار)‌کنه»

مگر این قضیه صفر و یکی است؟ چیزی که به نظر می‌رسد اینه غیر از اینه. من فکر می‌کنم که همه‌ی متون محاوره‌ای هستند که میزان به معیار نزدیک بودنش در طول جمله و متن تغییر می‌کنه.

**Comment by yassersouri** [comment]
@rasoolims @nournia 
یک منبعی پیدا کردم که اطلاعات ساختار مندی در مورد برخی از افعال محاوره‌ای زبان فارسی داره.

http://takvaj.ir/main/infinitive.php

**Comment by nournia** [comment]
<div dir=rtl>

من هم دوست دارم آقای رسولی بیشتر توضیح بدن در مورد چالش‌های این مساله. ولی خوبه توضیحاتی در مورد پیاده‌سازی کنونی ریشه‌یاب افعال بدم:

در حال حاضر ریشه‌یابی ما با استفاده از قانون‌های ساختن فعل در فارسی نیست. یعنی نگاه نمی‌کنیم ببینم مثلا `رفتم` با `م` تموم می‌شه و بگیم که شاید این فعل ماضی اول شخص مفرد باشه. دلیلش هم اینه که این کار **هم کلی حالت خاص داره** و **هم کلی قاعده می‌خواد** که سرعت رو کم می‌کنه.

در حال حاضر ما فهرستی از بن افعال فارسی داریم که تعدادشون هم زیاد نیست و با صرف کردن اونها یک دیکشنری درست می‌کنیم که فعل رو به بن تبدیل می‌کنه. یعنی قواعد رو برای صرف کردن به کار می‌بریم نه برای تجزیه کردن. اشکال این روش این هست که باید فهرست فعل‌هامون کامل باشه که با مرور زمان این کار رو می‌کنیم.

اما برای واژه‌های زبان محاوره، به نظر من تعداد فعل‌هایی که در زبان محاوره صرف می‌شن زیاد نیست و به همین دلیل، ساختن دیکشنری جداگانه‌ای برای این افعال کار بسیار راحتیه. شاید حتی نیاز به درست کردن قاعده‌مند فعل‌ها هم نباشه و بتونیم خود فهرست واژه‌های محاوره رو قرار بدیم. البته می‌دونم که برای شرایط پیچیده چنین کاری جواب نمی‌ده، مثلا تبدیل **کار راحتیه** در همین سطر به **کار راحتی هست** با چنین روشی خیلی موثر نیست.

لینکی هم که آقا یاسر گذاشته نقطه شروع خوبی هست برای تهیه فهرست واژه‌های محاوره و ریشه اونها.

**Comment by rasoolims** [comment]
شاید مسألهٔ شبیه به این در زبان عربی باشه که یک عربی معیار وجود دارد و گویش‌های مختلف مثل گویش شامی، گویش خلیجی، گویش مصری، گویش مراکشی، گویش مالتی و الی آخر. حالا خود این گویش‌های انواع دارند. مثلاً گویش عراقی با وجود نزدیکی به شام متفاوت هست. نکتهٔ شباهت این هست که مانند زبان فارسی، گویش‌ها زیاد به صورت اصولی مورد بررسی قرار نگرفته‌اند. شاید اگر روی کاغذ فکر کنید، به این نتیجه برسید که کار راحت هست ولی «که عشق آسان نمود اول ولی افتاد مشکل‌ها».
در هر حال، به نظرم صرف ریشه‌یابی کلمات زیاد به کار نمیاد. بیشتر باید به این نگاه کرد که با این ریشه‌یابی‌ها چه کار می‌خواهید کنید.

**Comment by reza1615** [comment]
سلام
در اینجا ما فهرستی از کلمات و افعال غیر رسمی را تهیه کردیم که این فهرست چندین ماه در ویکی‌پدیا بررسی شد و  چندین بار ویرایش شده‌است
https://fa.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87%E2%80%8C%DB%8C%D8%A7%D8%A8/%D9%81%D9%87%D8%B1%D8%B3%D8%AA/%D8%BA%DB%8C%D8%B1%D8%B1%D8%B3%D9%85%DB%8C
