### ISSUE TITLE
مشکل stemmer در هضم

### ISSUE THREAD

**Issue by fateme1373** [sobhe/hazm#181]
سلام . دوستان مشکل من این هست که وقتی از ریشه یاب هضم استفاده میکنم آخر بعضی کلمات رو میخوره!
مثلا "تلاش" رو میکنه "تلا"یعنی حرف اخرو میخوره
یا 
دوست رو تبدیل میکنه به"دوس" و..
ولی کتاب رو مثلا به درستیهمون کتاب ریشه یابی میکنه.
بریا اینکه به کلمات اسیب نزنه چیکار میتونم کنم؟
آیا کتابخونه خوب دیگه ای بریا پردازش زبان فارسی هست که این مشکلو نداشته باشه؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
این ويزگی‌هایی که می‌فرمایید مربوط هست به `Stemmer` و خب کار این ابزار همینه.
اون چیزی که شما دنبالش هستید `Lemmatizer` هست.
