### ISSUE TITLE
حذف stopword

### ISSUE THREAD

**Issue by lameei** [sobhe/hazm#183]
آیا تابعی هست که لیست توکن‌ها رو تحویل بگیره و استاپ‌وردها رو از توش حذف کنه؟

**Comment by nournia** [comment]
سلام
این تابع وجود نداره. ولی خب کد کوتاهی هست:

    from hazm import stopwords_list
    stopwords_set = set(stopwords_list())

    def filter_stopwords(input_tokens):
        return [token for token in input_tokens if token not in stopwords_set]
