### ISSUE TITLE
کار نکردن normalizer.normalize

### ISSUE THREAD

**Issue by makprogramer** [sobhe/hazm#189]
درود
بنده این کتابخانه را نصب کردم و کدهای زیر را نوشتم:
 
from __future__ import unicode_literals
from hazm import *

normalizer = Normalizer()
print(normalizer.normalize('سینما'))

ولی کلمه سینما به صورت حرف به حرف و برعکس چاپ میشود
همچنین برای خاصیت 
text
یک لیبل(در برنامه گرافیکی) با متن فارسی، خروجی تابع 
normalizer.normalize()
را به خاصیت تکست لیبل منتسب میکنم ولی باز هم مشکل دارد و اصلا هیچگونه تاثیری ندارد.
ممنون میشم راهنمایی کنید که مشکل کجاست؟
سپاس

نسخه پایتون بنده = 3.8.6
ادیتور=vscode 1.52.1
ویندوز 7 سرویس پک 1

**Comment by nournia** [comment]
<div dir="rtl">

سلام
اینکه متن رو حرف به حرف می‌بینید به خاطر این هست که واسط نمایش شما فارسی رو نمی‌تونه چاپ کنه.
متن رو در فایل بریزید تا بتونید به صورت درست ببینید خروجی رو.

برای تست نرمالایزر هم اول همون نمونه داخل README رو چک کنید.
احتمالا ورودی و خروجی رو باید دقیقتر بررسی کنید.
