### ISSUE TITLE
Ezafe recongnition

### ISSUE THREAD

**Issue by CrystalWLH** [sobhe/hazm#192]
How can I use this tool to get Ezafe recognition results? Looking forward to your answer~ Thanks very much！

**Comment by nournia** [comment]
Hi,
We do Ezafe recognition in POS tagging, so you need to use POSTagger class. Each tag name that ends with `e` character indicates that this word is in the Ezafe construction, for example `Ne` means Noun with Ezafe.

**Comment by CrystalWLH** [comment]
Got it~ Thanks very much.
