### ISSUE TITLE
Option to disable join_verb_parts in WordTokenizer?

### ISSUE THREAD

**Issue by nadirkhanlou** [sobhe/hazm#194]
Hello dear authors.

Is there a way I can set the join_verb_parts flag to False for the WordTokenizer?

I want the tokenizer to tokenize "نوشته می‌شود" into two separate tokens 'نوشته' and 'می‌شود', instead of the one token 'نوشته_می‌شود'.

Currently I am able to modify the source code in order to achieve my desired result, but I am looking for a way to set this flag as an option instead.

Thank you.

**Comment by kokabi1365** [comment]
This feature is now implemented.

You can pass join_verb_parts to WordTokenizer:

```python
>>> WordTokenizer(join_verb_parts=True)
	.tokenize('این کتاب به دست چه کسی نوشته می‌شود؟.')
```
[Read more](https://www.roshan-ai.ir/hazm/docs/content/modules/WordTokenizer/#hazm.WordTokenizer.WordTokenizer).
