### ISSUE TITLE
لیست برچسب‌ها (POS tag list)

### ISSUE THREAD

**Issue by NeginAbadani** [sobhe/hazm#197]
آیا راهی وجود داره که لیست کاملی از برچسب‌هایی که در مدل استفاده شده بدست بیاریم؟

**Comment by nournia** [comment]
<div dir=rtl>

لطفا اینجا رو ببینید: #58

**Comment by NeginAbadani** [comment]
> لطفا اینجا رو ببینید: #58

مجموعه ی برچسب‌ها در مقاله‌ی ارجاع داده شده شامل 109 برچسب هست. من به لیست دقیقی از مجموعه برچسب‌هایی که شما در کارتون استفاده کردید نیاز دارم، ممنون میشم اگر راهنمایی کنید.

**Comment by nournia** [comment]
<div dir=rtl>

سلام
این برچسب‌ها برای آموزش مدل تحلیل صرفی مورد استفاده قرار گرفتن که توضیح‌شون در مقاله داده‌ها هست:

     'N', 'V', 'AJ', 'ADV', 'PRO', 'DET', 'P', 'POSTP', 'NUM', 'CONJ', 'PUNC', 'CL', 'INT', 'RES'

البته در صورتی که واژه کسره اضافه داشته باشه حرف `e` به انتهای برچسب اضافه می‌شه. مثلا `Ne` برای اسم به همراه کسره اضافه هست.
