### ISSUE TITLE
Fixing the issue of half-space in some words

### ISSUE THREAD

**Issue by MeisamAmini** [sobhe/hazm#208]
As far as I know, we shouldn't use half-space or nimfaseleh after these seven letters: ا، د، ذ، ر، ز، ژ، و because they have a kind of natural spacing already. But when I normalize text with Hazm, it puts half-space after these (E.G. کشور ها becomes کشور‌ها).

**Comment by kokabi1365** [comment]
این مشکل فعلاً وجود نداره.
