### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by rashidasgari** [sobhe/hazm#21]
سلام من در سیستم عامل مک او اس وقتی می‌خوام توی ترمینال هضم رو برای پایتون نصب کنم در آخر مراحل نصب این ارور میاد:
error: could not create '/Library/Python/2.7/site-packages/hazm': Permission denied

**Comment by nournia** [comment]
این رو تست کنید:

    sudo pip install hazm

**Comment by mohagheghiyan** [comment]
مشکل من توی ویندوزه مگرنه قبلا روی لینوکس هضم را نصب کردم.

**Comment by rashidasgari** [comment]
mersi ba dastoore sudo nasb shod.

**Comment by nournia** [comment]
@mohagheghiyan 
پاسخ شما اینجاست: #20

**Comment by mohagheghiyan** [comment]
ممنون از جوابتوندرست شد.اما فکر کنم دلیل اصلی این  مشکل نصب بیش از یک نسخه از جاوا روی سیستمم بود.اما مسیری رو هم که داده بودید جواب داد.

**Comment by hosseinakbarian** [comment]
سلام من بعد از  و ایمپورتش  با خطای زیر مواجه میشم میشه بگید مشکل از کجاست؟

ImportError: No module named wapiti

**Comment by mgh790** [comment]
سلام منم دقیقا همین مشکل و دارم: 
بعد از نصب و ایمپورت کردن با چنین خطای روبرو میشم؟؟

ImportError: No module named wapiti

**Comment by nournia** [comment]
<div dir=rtl>

سلام
در بخش نصب هضم در [سایت](http://www.sobhe.ir/hazm/)، توضیح داده شده که چطور روی ویندوز نصب کنید.
فکر می‌کنم اگر از اون راه استفاده کنید، مشکل حل بشه.
