### ISSUE TITLE
Stemmer Algorithm 

### ISSUE THREAD

**Issue by MTanasan** [sobhe/hazm#210]
سلام جناب نوریان
اگر من درست متوجه شده باشم ماژول stemmer شما کلا هر چی الف آخر کلمات هست رو حذف می کند مثلا خدا به خد تبدیل می شود یا بها به به ....
به نظر این الگوریتم منطقی به نظر نمی رسد

**Comment by nournia** [comment]
سلام
ابزار stemmer یک ابزار داخلی هست در هضم، اگر قصد ریشه‌یابی واژه‌ها رو دارید لطفا از lemmatizer استفاده کنید.
