### ISSUE TITLE
Stemmer issue

### ISSUE THREAD

**Issue by MEgooneh** [sobhe/hazm#218]
کلمه ی حیوانات را حیو خروجی میدهد. احتمالا به دلیل اولویت دادن به "حیو**ان**ات" است.

**Comment by kokabi1365** [comment]
سلام.
باتوجه به اینکه استمر بر اساس یک‌سری قواعد سادهٔ زبانی کار می‌کنه وجود چنین مشکلاتی طبیعی است. در مثال شما ابتدا به ساکن «ات» به عنوان پسوند جمع‌ساز حذف می‌شه و بعد «ان» به عنوان پسوند جمع‌ساز بعدی حذف می‌شه و در نتیجه خروجی «حیو» رو خواهیم داشت. حتی در کتابخانه‌ها و زبان‌های دیگه هم این مشکل وجود داره و گاهی خروجی استمر کاملاً بی‌معناست. در این مورد قبلاً گفتگوهایی انجام شده است.

Duplicate of #34

**Comment by kokabi1365** [comment]
Duplicate of #34
