### ISSUE TITLE
ریشه یاب

### ISSUE THREAD

**Issue by hosseinip** [sobhe/hazm#23]
با سلام
در مورد ریشه یاب ابزار هضم فکر میکنم که بسیار خوب عمل میکنه ولی کارای بهتری هم شاید بشه انجام داد و در حال حاضر در حال بررسی هستم تا اگر بشه بهبودهایی رو بتونم اعمال کنم.
به طور مشخص قبل از اینکه کلمه به تابع ریشه یاب داده بشه شاید اعمال برخی از پیش پردازشها نتیجه کار رو بهتر کنه.

---

++ پانوشت: البته با توضیحات جناب نوریان متوجه شدم که در تابع نرمال سازی متن تا حدود زیادی اینکار انجام میشه

---

من تابع بسیار ساده ای در این رابطه آماده کردم که به محض تکمیل شدن به اشتراک میگذارم.

---

++ پانوشت: فکر نمیکنم فعلا نیازی به این تابع من وجود داشته باشه چون تابع نرمال سازی هضم دقیقا همینکار رو انجام میده

---

دوماً، در خصوص لیست پسوندهایی هم که در ریشه یاب آمده اند، میخواستم ببینم که آیا ترتیب در آنها لحاظ شده؟
ممنون میشم در هر کدام از موارد نظر دوستان رو هم بدونم

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خوشحالم که می‌خواید ریشه‌یاب رو ارتقا بدید، به این نکات لطفا توجه کنید:
+ پیش‌پردزاش‌ها رو ما بردیم در کلاس [نرمالایزر](https://github.com/sobhe/hazm/blob/master/hazm/Normalizer.py) که قبل از ریشه‌یابی باید فراخوانی بشه (مثلا همون اصلاح حرف ي یا موارد مشابه رو انجام می‌ده). کلا همه پردازش‌های زبانی نیاز به تمیز کردن متن دارند، یک کلاس درست کردیم که مجبور نباشیم در هر بخش متن رو تمیز کنیم.
+ ریشه‌یاب اگرچه [کد مختصری](https://github.com/sobhe/hazm/blob/master/hazm/Stemmer.py) داره ولی ترتیب قرارگیری پسوندها رو لحاظ می‌کنه، مثل این نمونه که دو مورد باید حذف بشه:

		>>> stemmer.stem('کتابهایشان')
		'کتاب'

کلاس لماتایزر هم از همین کد استمر کمک می‌گیره و با استفاده از واژه‌نامه و همچنین نقش صرفی واژه اگر مشخص باشه، در مورد ریشه تصمیم می‌گیره.

**Comment by hosseinip** [comment]
بسیار ممنون از نکات مفیدی که اشاره کردید، با توجه به این نکات من در اجرای مجدد خروجی به مراتب بهتری رو گرفتم
فقط اینکه ممکنه بسته به دامنه کلماتی که مورد استفاده قرار میگیرند پسوندهای دیگری هم وجود داشته باشند که شاید اعمال کردن آنها در ریشه یابی بد نباشد. به عنوان مثال ما حدود 60 نوع پسوند متنوع در زبان فارسی داریم. خواستم ببینم که آیا معیار مشخصی برای لیست فعلی از پسوندها وجود داشته؟

**Comment by nournia** [comment]
<div dir=rtl>
ما فعلا پسوندهای «جمع‌ساز، نکره‌ساز و ضمایر ملکی» رو قرار دادیم. که خب تعدادشون خیلی کمه. (بعلاوه پسوند «تر» و «ترین» هم چون خیلی پرتکرار هستند)
شاید پسوندهایی که مورد نظر شما هستند، بیشتر اشتقاقی باشند، مثل «گاه» در «کارگاه». تشخیص این ترکیب‌ها رو به امید خدا در تحلیل ریخت‌شناسی خواهیم داشت که فعلا پیاده‌سازی نشده و قراره از این [کد](https://sites.google.com/site/morfetteweb/home) استفاده کنیم. در واقع نمی‌خوایم قوانین متعدد برای تحلیل واژه تعریف کنیم.
در واقع ریشه‌یاب ما برای این طراحی شده که دقت تجزیه نحوی و بقیه پردازش‌های زبانی رو بالا ببره (یعنی همون «تر» و «ترین» رو هم شاید حذف کنیم).
ممنون می‌شم که در مورد پسوندها بیشتر توضیح بدید.

**Comment by hosseinip** [comment]
دقیقا همینطوره، پسوندهای اشتقاقی، نمونه هایی مثل پسوند اسم مکان ساز "زار" و "سار" به تریتب در کلماتی چون "لاله‌زار" و "کوهسار" و ...
البته با لیست فعلی که هر چند مختصر هست بعلاوه دو پسوند تفضیلی رایج "تر" و "ترین" که اشاره کردید دقت بسیار خوبی وجود داره.
ولی اگر دامنه متون رو تغییر بدیم و به عنوان مثال روی متون ادبی تر قصد کار داشته باشیم شاید در نظر گرفتن بعضی از پسوندهای اضافی هم ضرری نداشته باشه.
