### ISSUE TITLE
نصب پکیج libwapiti

### ISSUE THREAD

**Issue by hosseinip** [sobhe/hazm#24]
سلام،
در آخرین تغییرات انجام شده در هضم از تولکیت برچسب زن (wapiti) استفاده شده که با توجه به ویژگی های این تولکیت مسلماً اینکار  خیلی خوبه.
فقط اینکه من در نصب این پیکیج دچار مشکل شدم و به طبع پروژه رو در زبان پایتون نمیتونم اجرا کنم.
نسخه پایتون من 3.4 هست و فکر میکنم مشکل ناشی از عدم تطابق این نسخه با vc++ 2013 باشه که در حال حاضر دارم.
تا اونجا که متوجه شدم برای ویندوز و نسخه 3.3 به بعد پایتون نسخه vc++ 2010 باید مطابقت داشته باشه، ولی متاسفانه با نصب این ورژن هم من هنوز نتونستم که این پکیج رو نصب کنم. (در هنگام نصب خطای عدم پیدا شدن vcvarsall.bat رو میگیرم.)
میخواستم ببینم که آیا راه حلی برای این مشکل وجود داره؟
ممنون

**Comment by nournia** [comment]
<div dir=rtl>
سلام
همونطور که نوشتید در آخرین نسخه هضم از بسته libwapiti برای برچسب‌زن صرفی استفاده شده به خاطر سرعت و دقتش. نصب این بسته در سیستم عامل لینوکس و مک به آسونی انجام می‌شه. در واقع این بسته از کدهای `سی` استفاده می‌کنه که نیاز به کامپایل شدن دارند. اما اگر می‌خواید در ویندوز استفاده کنید، فعلا توصیه می‌کنم از نسخه قبلی استفاده کنید، یعنی:

	pip install hazm==0.4

البته ما داریم تلاش می‌کنیم نسخه مناسب ویندوز رو به صورت بسته `wheel` عرضه کنیم، ولی فعلا این کار انجام نشده.

**Comment by nournia** [comment]
<div dir=rtl>

[سایت هضم](http://www.sobhe.ir/hazm) برای آموزش نصب روی ویندوز به‌روز شد.

**Comment by mehraban72** [comment]
سلام این مشکل برای نصب توی لینوکس برای من رخ میده با اینکه 
python-dev هم نصب کردم ولی آخرین ورژن هضم بازم نصب نمیشه

**Comment by nournia** [comment]
<div dir=rtl>

سلام
ممکن هست توضیح بدید در مورد نحوه نصب و مشکلی که باهاش مواجه می‌شید؟
اگر نگاهی به این [لاگ دستورات](https://travis-ci.org/sobhe/hazm/jobs/535981259) بندازید، نحوه نصب هضم رو روی لینکوس و نتیجه اجرای دستورات رو می‌بینید.

**Comment by raminfp** [comment]
Please Install Common Dependencies:

```bash
$ sudo apt-get install build-essential
```
