### ISSUE TITLE
resources/postagger.model not found when working with the POSTagger

### ISSUE THREAD

**Issue by rashidasgari** [sobhe/hazm#25]
i get the following error when i try to use the POSTagger:

error: cannot open input model file: resources/postagger.model
	<No such file or directory>

**Comment by rashidasgari** [comment]
I just realized i havnt installed the models!

**Comment by zamaniali1995** [comment]
No I think there is an another problem in the source code since although I have installed the package, I am getting the same error.

**Comment by nournia** [comment]
Hi,
In the installation section of [hazm main page](http://www.sobhe.ir/hazm/) you can find simple instruction on how to download and extract resources folder.

**Comment by zamaniali1995** [comment]
Thanks for your response.
