### ISSUE TITLE
ریشه یابی افعال  واسامی بی قاعده (لاتین)

### ISSUE THREAD

**Issue by nasimp** [sobhe/hazm#26]
با سلام و احترام .من قصد دارم روی دیتا ست رویترز کار کنم .در فاز اول باید دیتا ست را نرمال سازی کنم و عملیات ریشه یابی را انجام دهم . . با توجه به این که دیتا ست من لاتین است .من چگونه می توانم  افعاد و اسامی بی قاعده را ریشه یابی کنم . ؟

**Comment by nournia** [comment]
<div dir=rtl>
ریشه‌یابی واژه‌های انگلیسی بسیار آسون هست و شما نیازی به استفاده از هضم ندارید. برای این کار می‌تونید از [این کلاس](http://www.nltk.org/_modules/nltk/stem/wordnet.html) استفاده کنید.

**Comment by nasimp** [comment]
‫در ۱ خرداد ۱۳۹۴ ه‍.ش.، ساعت ۲۲:۱۴‏، Alireza Nourian‏ <
notifications@github.com> نوشت:‏

>
> ریشه‌یابی واژه‌های انگلیسی بسیار آسون هست و شما نیازی به استفاده از هضم
> ندارید. برای این کار می‌تونید از این کلاس
> <http://www.nltk.org/_modules/nltk/stem/wordnet.html> استفاده کنید.
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/sobhe/hazm/issues/26#issuecomment-104724531>.
>
با سلام ،سپاس فراوان به خاطر پاسختان.
من زیاد به برنامه پایتون مسلط نیستم می شه لطف کنید نحوه استفاده از این کلاس
را توضیح دهید و این که من دیتا ست مد نظر خود را چگونه در این کلاس بگنجانم.

**Comment by nournia** [comment]
مثلا اینطوری

    >>> from nltk.stem import WordNetLemmatizer
    >>> wnl = WordNetLemmatizer()
    >>> print(wnl.lemmatize('aardwolves'))
   aardwolf

**Comment by nasimp** [comment]
2015-05-25 19:07 GMT+04:30 Alireza Nourian <notifications@github.com>:

> مثلا اینطوری
>
> >>> from nltk.stem import WordNetLemmatizer
> >>> wnl = WordNetLemmatizer()
> >>> print(wnl.lemmatize('aardwolves'))
>
> aardwolf
>
> سلام  اگه به این تابع یه فعل ingدار بدهیم خود اون فعل رو برمی گرداند
>

**Comment by nasimp** [comment]
‫در ۱۹ خرداد ۱۳۹۴ ه‍.ش.، ساعت ۹:۵۲‏، nasim parvizi‏ <parvizinasim@gmail.com>
نوشت:‏

>
> 2015-05-25 19:07 GMT+04:30 Alireza Nourian <notifications@github.com>:
>
>> مثلا اینطوری
>>
>> >>> from nltk.stem import WordNetLemmatizer
>> >>> wnl = WordNetLemmatizer()
>> >>> print(wnl.lemmatize('aardwolves'))
>>
>> aardwolf
>>
>>
>> اگر برای ریشه یابی از الگوریتم پورتر استفاده کنیم آیا مطمئن است؟
اگر بخواهیم فراوانی کلمات موجود در یک لیست را بدست آوریم  از چه دستوری
استفاده کنم به گونه ای که یک لیست از کلمات به ما بدهد که فراوانی هر کلمه
جلوی آن نوشته شده باشد .
دستور tabulate را در پایتون 3   چ گونه بنویسم ؟
با تشکر

>
>
>

**Comment by nournia** [comment]
دلیلش اینه که بهش برچسب صرفی رو ورودی نمی‌دید

    >>> print(wnl.lemmatize('running', pos='v'))
    run
    print(wnl.lemmatize('went', pos='v'))
    go

برای شمارش کلمات هم می‌تونید از [این کلاس](https://docs.python.org/3/library/collections.html#collections.Counter) استفاده کنید

این سوال‌ها به هضم ربطی ندارن و با کمی جستجو جواب‌شون رو پیدا می‌کنید

**Comment by nasimp** [comment]
‫در ۱۹ خرداد ۱۳۹۴ ه‍.ش.، ساعت ۱۲:۵۳‏، Alireza Nourian‏ <
notifications@github.com> نوشت:‏

> دلیلش اینه که بهش برچسب صرفی رو ورودی نمی‌دید
>
> >>> print(wnl.lemmatize('running', pos='v'))
> run
> print(wnl.lemmatize('went', pos='v'))
> go
>
> برای شمارش کلمات هم می‌تونید از این کلاس
> <https://docs.python.org/3/library/collections.html#collections.Counter>
> استفاده کنید
>
> این سوال‌ها به هضم ربطی ندارن و با کمی جستجو جواب‌شون رو پیدا می‌کنید
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sobhe/hazm/issues/26#issuecomment-110273395>.
>
ممنون از پاسختون ...ببخشید من نمی دونستم این سوالات را نباید از شما می
پرسیدم .......شاید این سوالات از نظر شما پیش پا افتاده باشن اما من تازه
وارد این حوزه شدم و صفر صفرم و چاره ایی نداشتم وگرنه هیچ وقت مزاحم شما نمی
شدم...........بازم ممنون. خدانگهدار

**Comment by nasimp** [comment]
‫در ۱۹ خرداد ۱۳۹۴ ه‍.ش.، ساعت ۱۴:۰۵‏، nasim parvizi‏ <parvizinasim@gmail.com
> نوشت:‏

>
> ‫در ۱۹ خرداد ۱۳۹۴ ه‍.ش.، ساعت ۱۲:۵۳‏، Alireza Nourian‏ <
> notifications@github.com> نوشت:‏
>
> دلیلش اینه که بهش برچسب صرفی رو ورودی نمی‌دید
>>
>> >>> print(wnl.lemmatize('running', pos='v'))
>> run
>> print(wnl.lemmatize('went', pos='v'))
>> go
>>
>> برای شمارش کلمات هم می‌تونید از این کلاس
>> <https://docs.python.org/3/library/collections.html#collections.Counter>
>> استفاده کنید
>>
>> این سوال‌ها به هضم ربطی ندارن و با کمی جستجو جواب‌شون رو پیدا می‌کنید
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sobhe/hazm/issues/26#issuecomment-110273395>.
>>
> سلام وقتتون بخیر ببخشید مزاحم می شم معذرت می خوام من از این دستور
> cfd.tabulate(conditions=genres, samples=modals) برای این که داده هایم را به
> همچین شکلی در بیاورم
>
                                                      can could  may might
must will
           news   93   86   66   38   50  389
       religion   82   59   78   12   54   71
        hobbies  268   58  131   22   83  264
science_fiction   16   49    4   12    8   16
        romance   74  193   11   51   45   43
          humor   16   30    8    8    9   13

استفاده کردم اما با توجه به این که تعداد سطر هه و ستون های من خیلی زیاد است
(چند هزارتا)این دستور ماتریس جالبی به من نمی دهد .من از چه دستوری می تونم
استفاده کنم با سپاس فراوان.

**Comment by nasimp** [comment]
‫در ۱ تیر ۱۳۹۴ ه‍.ش.، ساعت ۸:۳۵‏، nasim parvizi‏ <parvizinasim@gmail.com>
نوشت:‏
