### ISSUE TITLE
مشکل در ابزار برچسب زن با وجود قرار دادن مدل ها

### ISSUE THREAD

**Issue by davoodmf** [sobhe/hazm#27]
با سلام
ضمن تشکر از سازندگان مجموعه ی هضم بنده مشکلی که دارم مربوط به برچسب زن اجزای کلام یا POS Tager هست. 
من این ابزار را دانلود و درمحیط اکلیپس وارد کردم. بیشتر بخش های ابزار کار می کنند. اما هر کاری کردم، بخش برچسب زن جزء کلام و پارسر نحوی کار نکردند.
بنده مدل ها را نیز دانلود و در پوشه resources قرار دادم. برای برچسب زنی، اجرای دستور زیر خطا می دهد. 

دستور:

tagger = POSTagger(model='resources/postagger.model')
tagger.tag(word_tokenize('ما بسیار کتاب می‌خوانیم'))

خطا:

    tagger = POSTagger(model='resources/postagger.model')
  File "C:\Users\Ali\workspace\testhazm2\hazm\POSTagger.py", line 13, in __init_
_
    super(stanford.POSTagger, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'model

با تشکر

**Comment by nournia** [comment]
سلام
 ظاهرا شما آخرین نسخه هضم رو نصب نکردید

**Comment by davoodmf** [comment]
سلام
من نسخه ی هضم را که داشتم پاک کردم و  pip install hazm  را در پوشه ی C:\Anaconda3\Scripts اجرا کردم. موقع نصب خطای زیر گزارش داده شد. (البته من کل پیامهای پس از اجرا را آوردم)
C:\Anaconda3\Scripts>pip install hazm
Downloading/unpacking hazm
  Running setup.py (path:C:\Users\Ali\AppData\Local\Temp\pip_build_Ali\hazm\setu
p.py) egg_info for package hazm

Requirement already satisfied (use --upgrade to upgrade): nltk>=3.0.2 in c:\anac
onda3\lib\site-packages (from hazm)
Downloading/unpacking libwapiti>=0.2.1 (from hazm)
  Running setup.py (path:C:\Users\Ali\AppData\Local\Temp\pip_build_Ali\libwapiti
\setup.py) egg_info for package libwapiti

Requirement already satisfied (use --upgrade to upgrade): six in c:\anaconda3\li
b\site-packages (from libwapiti>=0.2.1->hazm)
Installing collected packages: hazm, libwapiti
  Running setup.py install for hazm

  Running setup.py install for libwapiti

    building 'libwapiti' extension
    C:\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -Icwapiti/src -Ilibwapiti -IC:\A
naconda3\include -IC:\Anaconda3\include -c cwapiti/src/bcd.c -o build\temp.win32
-3.4\Release\cwapiti\src\bcd.o -std=c99
    C:\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -Icwapiti/src -Ilibwapiti -IC:\A
naconda3\include -IC:\Anaconda3\include -c cwapiti/src/decoder.c -o build\temp.w
in32-3.4\Release\cwapiti\src\decoder.o -std=c99
    In file included from cwapiti/src/decoder.c:43:0:
    cwapiti/src/thread.h:32:21: fatal error: pthread.h: No such file or director
y
    compilation terminated.
    error: command 'C:\\Anaconda3\\Scripts\\gcc.bat' failed with exit status 1
    Complete output from command C:\Anaconda3\python.exe -c "import setuptools,
tokenize;__file__='C:\\Users\\Ali\\AppData\\Local\\Temp\\pip_build_Ali\\libwapit
i\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().repla
ce('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Ali\AppData\Loca
l\Temp\pip-jfhq2cx8-record\install-record.txt --single-version-externally-manage
d --compile:
    running install

running build

running build_py

creating build

creating build\lib.win32-3.4

creating build\lib.win32-3.4\wapiti

copying wapiti\api.py -> build\lib.win32-3.4\wapiti

copying wapiti\script.py -> build\lib.win32-3.4\wapiti

copying wapiti\__init__.py -> build\lib.win32-3.4\wapiti

running egg_info

writing top-level names to libwapiti.egg-info\top_level.txt

writing libwapiti.egg-info\PKG-INFO

writing dependency_links to libwapiti.egg-info\dependency_links.txt

writing requirements to libwapiti.egg-info\requires.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'libwapiti.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'libwapiti.egg-info\SOURCES.txt'

running build_ext

building 'libwapiti' extension

creating build\temp.win32-3.4

creating build\temp.win32-3.4\Release

creating build\temp.win32-3.4\Release\cwapiti

creating build\temp.win32-3.4\Release\cwapiti\src

creating build\temp.win32-3.4\Release\libwapiti

creating build\temp.win32-3.4\Release\libwapiti\src

C:\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -Icwapiti/src -Ilibwapiti -IC:\Anaco
nda3\include -IC:\Anaconda3\include -c cwapiti/src/bcd.c -o build\temp.win32-3.4
\Release\cwapiti\src\bcd.o -std=c99

C:\Anaconda3\Scripts\gcc.bat -mdll -O -Wall -Icwapiti/src -Ilibwapiti -IC:\Anaco
nda3\include -IC:\Anaconda3\include -c cwapiti/src/decoder.c -o build\temp.win32
-3.4\Release\cwapiti\src\decoder.o -std=c99

In file included from cwapiti/src/decoder.c:43:0:

cwapiti/src/thread.h:32:21: fatal error: pthread.h: No such file or directory

compilation terminated.

error: command 'C:\\Anaconda3\\Scripts\\gcc.bat' failed with exit status 1

----------------------------------------
Cleaning up...
Command C:\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\Us
ers\\Ali\\AppData\\Local\\Temp\\pip_build_Ali\\libwapiti\\setup.py';exec(compile
(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file_
_, 'exec'))" install --record C:\Users\Ali\AppData\Local\Temp\pip-jfhq2cx8-recor
d\install-record.txt --single-version-externally-managed --compile failed with e
rror code 1 in C:\Users\Ali\AppData\Local\Temp\pip_build_Ali\libwapiti
Storing debug log for failure in C:\Users\Ali\pip\pip.log

C:\Anaconda3\Scripts>

**Comment by yassersouri** [comment]
سلام.

تا اونجایی که من می‌دونم این مشکلی است که روز ویندوز داریم و فعلا راه حلی
براش پیدا نشده. پیشنهاد می‌کنم از پلتفورم‌های دیگه مثل لینوکس استفاده کنید.

**Comment by davoodmf** [comment]
خیلی ممنون 
در لینوکس امتحان می کنم
امیدوارم که جواب بدهد

**Comment by yassersouri** [comment]
به نظر من این دستور رو اجرا کنید
sudo apt-get install build-essential
sudo apt-get install python-pip
sudo pip install hazm

2015-05-23 17:51 GMT+04:30 davoodmf <notifications@github.com>:

**Comment by davoodmf** [comment]
در لینوکس نیاز به برنامه ی خاصی به عنوان پیش نیاز نیست؟

**Comment by yassersouri** [comment]
چیز خاصی یادم نمیاد. همین دستوراتی که گفتم رو که اجرا کنید درست می‌شه
احتمالا.

**Comment by davoodmf** [comment]
خیلی ممنون از راهنماییتون

**Comment by davoodmf** [comment]
با سلام
من دستورات مربوط به نصب هضم را در ابونتو اجرا کردم
 مدلها را هم در پوشه ی زیر کپی کردم
/usr/local/lib/python2.7/dist-packages/hazm/resources

من از خط فرمان پایتون استفاده کردم

اما پس از اجرای دستور زیر
tagger=POSTagger(model='resources/postagger.model')

این خطا گزارش شد
error: cannot open input model file: resources/postagger.model
	<No such file or directory>
به نظر شما مشکل از کجاست؟

**Comment by davoodmf** [comment]
من مسیر فایلها را به صورت کامل وارد کردم و مشکل حل شد

 tagger = POSTagger(model='/usr/local/lib/python2.7/dist-packages/hazm/resources/postagger.model')

با تشکر

**Comment by nournia** [comment]
سلام
با توجه به اینکه به صورت نسبی آدرس دادید، باید پوشه مدل‌ها رو بذارید کنار خود اسکریپت‌تون
