### ISSUE TITLE
مشکل در پارس کردن جملات با هضم

### ISSUE THREAD

**Issue by mitra8814** [sobhe/hazm#28]
ضمن عرض سلام و خسته نباشید.
بنده اوبونتو۱۴.۰۴ رو روی سیستمم نصب کردم سپس هضم نسخه ی ۵ رو هم روی پایتون ۳ نصب کردم و در نهایت هم فایل 
resources
را دانلود و در پروژه قرار دادم.
همه چیز به درستی پیش میره تا اینکه به این خط کد میرسم:
parser.parse(word_tokenize('زنگها برای که به صدا درمیآید؟'))
و خطای زیر داده میشه:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/nltk/parse/api.py", line 45, in parse
    return next(self.parse_sents([sent], *args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/hazm/DependencyParser.py", line 24, in parse_sents
    return self.tagged_parse_sents(tagged_sentences, verbose)
  File "/usr/local/lib/python3.4/dist-packages/hazm/DependencyParser.py", line 27, in tagged_parse_sents
    input_file = tempfile.NamedTemporaryFile(prefix='malt_input.conll', dir=self.working_dir, delete=False)
  File "/usr/lib/python3.4/tempfile.py", line 599, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python3.4/tempfile.py", line 339, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'resources/malt_input.conllzhh502l2'
ممنون میشم بفرمایید دلیل ایجاد چنین خطایی چیه؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
مطمئن هستید که کنار محل اجرای پروژه‌تون پوشه resources وجود داره؟

**Comment by mitra8814** [comment]
دقیقا در آدرس زیر
/usr/local/lib/python3.4/dist-packages/hazm 
پوشه ی 
resources
رو قرار دادم.
به  نظرتون درسته؟

**Comment by nournia** [comment]
این پوشه رو  در پروژه خودتون درست کنید. یعنی کنار همون کدی که اجرا می‌کنید

**Comment by mitra8814** [comment]
با عرض سلام مجدد و سپاس بی نهایت به دلیل پشتیبانی و راهنمایی خوب شما.
همانگونه که فرموده بودید تونستم مشکل رو حل کنم.
حال سوال بعدی بنده اینه که
وقتی کد
parser.parse(word_tokenize('زنگها برای که به صدا درمیآید؟'))
اجرا میشهُ در خروجی تنها خط زیر نوشته می شود:
<DependencyGraph with 8 nodes>

درواقع تنها اطلاع میده که گراف وابستگی ساخته شده اما اون رو نشون نمیده. ولی من نیاز دارم تا گراف وابستگی که ساخته شده رو مشاهده کنم. چطور میتونم این گراف که ساخته شده رو به دست بیارم و مشاهده کنم؟

**Comment by mitra8814** [comment]
ببخشید یک خط از سوالم نوشته نشده. مجددا سوال رومطرح می کنم:

وقتی کد
parser.parse(word_tokenize('زنگها برای که به صدا درمیآید؟'))
اجرا میشه. در خروجی تنها خط زیر نوشته می شود:
<DependencyGraph with 8 nodes>
درواقع تنها اطلاع میده که گراف وابستگی ساخته شده اما اون رو نشون نمیده. ولی من نیاز دارم تا گراف وابستگی که ساخته شده رو مشاهده کنم. چطور میتونم این گراف که ساخته شده رو به دست بیارم و مشاهده کنم؟

**Comment by nournia** [comment]
خروجی رو به این صورت می‌تونید چاپ کنید:

    parser.parse(word_tokenize('زنگها برای که به صدا درمیآید؟')).to_conll(10)

از این سایت می‌تونید برای نمایش خروجی استفاده کنید:
http://www.sobhe.ir/dependency-parse-tree/

البته این کارها برای نمایش هست و اگر واقعا با درخت تجزیه نحوی کار دارید، خروجی همون تابعی که نوشتید از این کلاس هست:
http://www.nltk.org/_modules/nltk/parse/dependencygraph.html

و برای پردازش بسیار مناسبه

**Comment by mitra8814** [comment]
خروجی هم نمایش داده شد. از راهنماییهای شما و  هم چنین در اختیار گذاشتن این پروژه نهایت تشکر را دارم.
امیدوارم همیشه موفق و سربلند باشید.
