### ISSUE TITLE
خواندن از فایل

### ISSUE THREAD

**Issue by atefeh92** [sobhe/hazm#29]
سلام خسته نباشید
ببخشید من یک سوال داشتم ممنون میشم که کمکم کنید 
من پایتون3 ا روی اوبونتو نصب کردم 
import os.path
scriptpath=os.path.dirname("/home/atefeh/Documents/")
filename=os.path.join(scriptpath,"testfile.txt")
fileres=open(filename)
ولی موقع خواندن از فایل خطای زیر را می دهد
 و بعد خطای زیر را می دهد:
filenotfounder: no such file or directory: /home/atefeh/documents
ولی وقتی پوشه را باز میکنم دقیقا این فایل وجود دارد
و با دستور sudo allocate testfile.txt
هم همان مسیر بالا را می دهد
ممنون میشم راهنماییم کنید

**Comment by atefeh92** [comment]
میخوام از فایل بخونم و با هضم توکن بندی کنم؟ که به خطای بالا برخورد کردم

**Comment by yassersouri** [comment]
سلام

دقیق مشخص نیست که قصد شما چه چیزی است ولی فکر کنم اگر این کار رو انجام بدید درست بشه.
```
filename = os.path.join("/home/atefeh/Documents/", "testfile.txt")
```

**Comment by yassersouri** [comment]
لطفا سؤال‌هایی که مستقیم به هضم مربوط نمی‌شود رو در جایی دیگر سؤال کنید.

با تشکر
