### ISSUE TITLE
مشکل کاراکتر نیم فاصله

### ISSUE THREAD

**Issue by mitra8814** [sobhe/hazm#30]
با عرض سلام
روی اوبونتو ۱۴.۰۴ و پایتون۳، هضم ۵ رو نصب کردم
هنگام اجرای این دستور در کنسول:

normalizer.normalize('اصلاح نويسه ها و استفاده از نیم فاصله پردازش را آسان مي كند')

خروجی به صورت زیر چاپ می شود:

'اصلاح نویسه\u200cها و استفاده از نیم\u200cفاصله پردازش را آسان می\u200cکند'

 مشکل اینه که کاراکتر نیم فاصله رو به صورت 
\u200c
چاپ می کنه.
ممنون میشم کمک کنین و بفرمایین این مشکلو چطور رفع کنم؟

**Comment by nournia** [comment]
سلام
این مشکل نیست، پایتون کاراکتر نیم‌فاصل رو این طوری نشون می‌ده
این طوری می‌تونید نوشته واقعی رو ببینید:

    print(normalizer.normalize('اصلاح نويسه ها و استفاده از نیم فاصله پردازش را آسان مي كند'))
