### ISSUE TITLE
dependency parser

### ISSUE THREAD

**Issue by atefeh92** [sobhe/hazm#31]
با عرض سلاو و خسته نباشید.
یک سوال داشتم ممنون میشم راهنماییم کنید، من می خواهم هر رشته ای را به صورت خط به خط اط فایل می خوانم و  با
posttagger 
برچسب گداری میکنم  و بعد با درخت پارس رابطه ی آن را بدست می آورم،حال چطور می توانم خروجی حاصل از درخت پارس را بگیرم تا در یک رشته بریزم  تا بتوانم در فایل دخیره کنم؟

**Comment by nournia** [comment]
سلام
نگاهی  به این #28  سوال بندازید.
