### ISSUE TITLE
پردازش متون عامیانه و غیر رسمی

### ISSUE THREAD

**Issue by hosseinip** [sobhe/hazm#32]
با سلام،
یکی از چالشهایی که امروزه در پردازش زبان طبیعی وجود داره طبیعتا کار با متون نوشتاری عامیانه و غیر رسمی هست.
در نسخه حاضر هضم تا اونجا که میدونم اینکار انجام نمیشه؟ به طور مشخص در مورد ریشه یابی کلمات غیر رسمی (نظیر آنچه به وفور در کامنتهای کاربران و یا پیامهای کوتاه مشاهده میشه)
خواستم ببینم آیا برنامه ای در این رابطه دارید؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
این موضوع قبلا مطرح شده، خوبه شما هم نگاه بندازید: #18 

کار مهمی هست و ما هم در آینده قصد انجامش رو داریم
یک نیازی که برای انجام این کار داریم، فراهم کردن حجم زیادی متن محاوره مثل کامنت و این جور چیزاست
بعد می‌تونیم به امید خدا روی توسعه ریشه‌یاب و احتمالا درست کردن یک واژه‌نامه کار کنیم

**Comment by reza1615** [comment]
سلام
در اینجا ما فهرستی از کلمات و افعال غیر رسمی را تهیه کردیم که این فهرست چندین ماه در ویکی‌پدیا بررسی شد و چندین بار ویرایش شده‌است
https://fa.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D8%A7%D8%B4%D8%AA%D8%A8%D8%A7%D9%87%E2%80%8C%DB%8C%D8%A7%D8%A8/%D9%81%D9%87%D8%B1%D8%B3%D8%AA/%D8%BA%DB%8C%D8%B1%D8%B1%D8%B3%D9%85%DB%8C

**Comment by hosseinip** [comment]
این لیست میتونه مفید باشه

**Comment by nournia** [comment]
بسیار عالی
به امید خدا از این واژه‌ها در تکمیل [ابزار پردازش محاوره](https://github.com/sobhe/hazm/blob/master/hazm/InformalNormalizer.py) استفاده می‌کنیم.
