### ISSUE TITLE
چگونگی رفرنس دهی + پیشنهاد

### ISSUE THREAD

**Issue by masoudian** [sobhe/hazm#33]
سلام وقتتون بخیر

سوالم اینه که چطور باید به هضم رفرنس بدم؟
کاش در همون سایت سبحه نمونه هایی مثل بیب-تکس رو هم اضافه کنید.

پیشنهاد:
 (stopword removal) .چیزی که میتونید اضافه کنید، حذف کلمات اضافی است
 همین طور حذف علائم نگارشی متن.

و کاش تبلیغات بیشتری در معرفی این پروژه انجام میگرفت 
چون من خیلی شانسی سایت هضم رو پیدا کردم، متاسفانه خیلی سخت می شه با گوگل این سایت رو پیداش کرد

با تشکر فراوان از زحمتی که کشدید..

**Comment by nournia** [comment]
<div dir=rtl>
سلام 
هضم فعلا مقاله‌ای یا راهنمایی برای ارجاع نداره. همین که لینک هضم  رو قرار بدید خوبه:
http://www.sobhe.ir/hazm/

البته به امید خدا تا یک ماه دیگه لینک مقاله‌ای رو در سایت قرار می‌دم که در مورد استفاده از کسره اضافه در هضم برای بالا بردن دقت تجزیه‌گر نحوی و همچنین تجزیه سطحی در هضم توضیح داده. شاید اگر این بخش‌ها به کارتون مربوط بشه بتونید بهش ارجاع بدید.

از نکاتی که گفتید هم ممنونم، لیست استاپ‌وردها رو هم به امید خدا خیلی زود قرار می‌دیم

**Comment by masoudian** [comment]
ممنون از پاسختون
چطور میشه از تغییرات آینده ی  پروژه باخبر شد؟
و اگه لیست استاپ وردها رو آماده دارید خیلی ممنون میشم در اختیارم قرار بدید..

**Comment by nournia** [comment]
<div dir=rtl>

می‌تونید از این لیست‌ها استفاده کنید:
http://www.google.com/search?q=A+List+of+Farsi+Stopwords
http://www.ranks.nl/stopwords/persian

ما هم لیستی رو از استاپ‌وردها داریم آماده می‌کنیم که هر وقت آماده بشه همین‌جا اطلاع می‌دم
