### ISSUE TITLE
مشکل با به روز رسانی کتاب خانه stanford

### ISSUE THREAD

**Issue by navidnabavi** [sobhe/hazm#35]
POSTagger به StanfordPOSTagger تغییر نام یافته است وبه همین دلیل با ورژن جدید أن ناسازگار است

**Comment by navidnabavi** [comment]
با NLTK جدید سازگار نیست

**Comment by nournia** [comment]
<div dir=rtl>
فکر کنم اگر هم هضم و هم nltk رو آپدیت کنید، درست بشه.

**Comment by navidnabavi** [comment]
مشکل همینه که آپدیت می شه به مشکل می خوره
nltk==3.0.3 که نصب می شه که آخرین آپدیت هستش این مشکل رو ایجاد می کنه
اما با nltk==3.0.2 سازگاره
علت همون تغییر نام هستش من با تغییر جزیی کد رو با هردو ورژن سازگار کردم

**Comment by nournia** [comment]
<div dir=rtl>
این مشکل در نسخه در حال توسعه حل شده. می‌تونید اینجوری آخرین نسخه رو نصب کنید:

    pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by navidnabavi** [comment]
ممنون فقط هرچه سریعتر pypi به روز شه خیلی ممنون می شم. چون نصب روی سرور بر اساس requirements.txt هستش و به اون شکل خیلی اصولی تر می شه برای ما. در هر صورت متشکر

**Comment by nournia** [comment]
<div dir=rtl>
این کار رو حتما انجام می‌دیم ولی شما می‌تونید در فایل نیازمندی‌ها به جای اسم پکیج همون آدرسی رو که نوشتم بنویسید.

**Comment by nournia** [comment]
<div dir=rtl>
در نسخه جدید عرضه شده این مشکل رو حل کردیم.
