### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by atefeh92** [sobhe/hazm#36]
سلام روزتون به خیر
یه سوال داشتم من وقتی با پارسر هضم یه فایل را پارس میکنم اکثر جملات را اشتباه پارس میکنه؟؟ در صورتیکه اگه همون جمله را به صورت تکی بش بدم درست پارس میکنه. به نظرتون چه کار کنم؟

**Comment by nournia** [comment]
<div dir=rtl>
خب باید اول متن رو جمله جمله بکنید و بعد بهش بدید. می‌تونید از تابع `sent_tokenize` استفاده کنید.

**Comment by atefeh92** [comment]
با سپاس فراوان از جواب شما
من به صورت زیر نوشته بودم:
 line = unicode(line.strip(),encoding='utf-8')
		                tokens = word_tokenize(line)
		                tagsen=tagger.tag(tokens)
				lineStem = ' '.join(i[0] + '/' + i[1] for i in tagsen)
		                treeSen=parser.parse(word_tokenize(lineStem))
		                fwStemPars.write(treeSen.to_conll(10).encode("utf-8"))
				fwStemPars.write("\n")
البته این کد در حلقه  است . به نظرتان اشتباهه؟
الته با این کد مشکل بالا را دارم

**Comment by nournia** [comment]
سلام
لطفا همونطور که پیشنهاد کردم، استفاده کنید
