### ISSUE TITLE
Parser Problem

### ISSUE THREAD

**Issue by atefeh92** [sobhe/hazm#37]
ببخشید من کد را پارس میکنم ولی در حلقه بینهایت می افتد ، به نظر شما مشکل خاصی داره. ممنون میشم راهنماییم کنید چون انواع روش ها را تست کردم
fileOpinionStem="StemPos"
filewStemPars="StemPars"
with open(filewStemPars,"w+") as fwStemPars:
            with open(fileOpinionStem,"r") as fr:
                    for line in fr:
            try:
                        line = unicode(line.strip(),encoding='utf-8')
                sentences = sent_tokenize(normalizer.normalize(line))

```
            treeSen=parser.parse_sents([word_tokenize(sentence) for sentence in sentences])
                    fwStemPars.write(treeSen.to_conll(10).encode("utf-8"))
            fwStemPars.write("\n")

        except Exception as e:
                            fwStemPars.write( "???????????????????????\n")
```

**Comment by atefeh92** [comment]
with open(filewStemPars,"w+") as fwStemPars:
        	with open(fileOpinionStem,"r") as fr:
                    for line in fr:
			try:
		                line = unicode(line.strip(),encoding='utf-8')
				sentences = sent_tokenize(normalizer.normalize(line))
		          
				treeSen=parser.parse_sents([word_tokenize(sentence) for sentence in sentences])
				for tree in treeSen:
			                fwStemPars.write(tree.to_conll(10).encode("utf-8"))
					fwStemPars.write("\n")
				print(treeSen.to_conll(10).encode("utf-8"))
				
			except Exception as e:
                                fwStemPars.write( "???????????????????????\n")
				
ببخشید من کد را به صورت بالا تغییر دارم ولی باز هم اشتباه پارس می کند.فایل ورودی هم فایل برچسب گذاری شده با ابزار هضم است.
 ممنون میشم کمکم کنید

**Comment by nournia** [comment]
همونطور که در مثال صفحه اول اومده، جمله‌هایی که به پارسر می‌دید رو لازم نیست برچسب‌گذاری کنید:

    parser = DependencyParser(tagger=tagger, lemmatizer=lemmatizer)
    parser.parse(word_tokenize('زنگ‌ها برای که به صدا درمی‌آید؟'))

همچنین با کمک یک ابزار دیباگر می‌تونید بیشتر مشکلات کدهاتون رو پیدا کنید. مثلا این خوبه
https://www.jetbrains.com/pycharm/
