### ISSUE TITLE
علت افت دقت پارس

### ISSUE THREAD

**Issue by mitra8814** [sobhe/hazm#38]
با عرض سلام و خسته نباشید
ببخشید بنده ابتدا اومدم و تمام جملات مورد نظرم رو داخل فایلی ریختم و سپس اون فایل رو به پارسر هضم دادم تا تک تک جملات موجود در فایل را پارس کند. اما به نظر می رسد دقت پارس نسبت به زمانی که جملات به صورت دستی یکی یکی به هضم داده می شوند، پایین می آید. به نظر شما علت چیست؟

کد بنده نیز به صورت زیر است:
with open(filewStemPars,"w+") as fwStemPars:
with open(fileOpinionStem,"r") as fr:
for line in fr:
try:
line = unicode(line.strip(),encoding='utf-8')
normalizer = Normalizer()
sentences = sent_tokenize(normalizer.normalize(line))
            treeSen=parser.parse_sents([word_tokenize(sentence) for sentence in sentences])
            for tree in treeSen:
                        fwStemPars.write(tree.to_conll(10).encode("utf-8"))
                fwStemPars.write("\n")
            print(treeSen.to_conll(10).encode("utf-8"))

        except Exception as e:
                            fwStemPars.write( "???????????????????????\n")

**Comment by nournia** [comment]
نکته‌ای که می‌گید خیلی عجیبه، نباید این طوری باشه
