### ISSUE TITLE
درخواست توضیح در مورد برخی برچسب های اجزای کلام

### ISSUE THREAD

**Issue by davoodmf** [sobhe/hazm#39]
با سلام و عرض خسته نباشید

در برچسب زنی اجزای کلام در مورد دو نشانه ی زیر که مشخص کردم اگر ممکن است توضیح دهید 
چون در تگ های پیکره ی بیجن خان که در یکی از تاپیک های این بخش آمده این برچسب ها  نبودند 
RES
RESe

با تشکر

**Comment by nournia** [comment]
<div dir=rtl>
برچسب RES متعلق به پیکره دکتر بی‌جن‌خان هست.
در مقاله پیکره از این پرچسب به عنوان Residual اومده و  به معنی هرچیزی غیر از برچسب‌های دیگه هست
مثلا واژه‌ها یا عبارات انگلیسی یا عربی، این نمونه‌ها از پیکره آورده شدن:

    نه
    آری
    New Line Cinema
    یعجبک
    تبارک الله

اما برچسب e که انتهای هر برچسب دیگری میاد، به معنی وجود کسره اضافه هست
