### ISSUE TITLE
نحوه کارکرد برچسب زن نقش کلمات

### ISSUE THREAD

**Issue by hosseinip** [sobhe/hazm#40]
با سلام
میخواستم بدونم که آیا کارکرد برچسب زن اجزای سخن ارتباطی با ساختار جمله هم داره؟ و به صورت مشخص آیا بین دو حالت زیر تفاوتی وجود داره؟
اول حالتی که یک متن رو بدون مشخص کردن جملات و به یکباره به برچسب زن بدیم و دوم حالتی که ابتدا متن رو به جملات شکسته و هر جمله رو به تنهایی به برچسب زن بدیم. یعنی عملکرد برچسب زن به اینکه متن در قالب جمله باشه یا خیر بستگی داره؟ در حال حاضر در صورت تعداد ورودی های بالا چون هر بار نیاز به فراخوانی مدل فایل هست برای زمانی که تعداد ورودی ها یا جملات زیادی داشته باشیم سرعت اجرا به شدت پایین و زمان اجرا طبیعتا بالاست
خواستم ببینم که اگر تفاوتی بین دو حالت یاد شده نیست در پیاده سازی لزوما جملات رو جداسازی نکنم
ممنون

**Comment by nournia** [comment]
سلام
اینکه متن جمله جمله باشه برای برچسب‌زن صرفی خیلی مهمه و در دقتش تاثیر زیادی داره
برای اینکه بهترین سرعت رو بگیرید، اینطوری استفاده کنید:

    sentences = [word_tokenize(sentence) for sentence in sent_tokenize(normalizer.normalize(text))]
    tagger.tag_sents(sentences)

آخرین نسخه هضم با این روش چند هزار جمله رو در ثانیه تحلیل می‌کنه
