### ISSUE TITLE
درخواست توضیحات برچسب های جزء کلام هضم و سوال در مورد دادگان

### ISSUE THREAD

**Issue by davoodmf** [sobhe/hazm#41]
با سلام
می خواستم برای برچسب های جز کلام که هضم تگ می زنه مرجعی معرفی کنید که مشخص کنه هر tag مربوط به چه نوع کلمه ای است. البته بیشترش رو متوجه شدم ولی هنوز در مورد برخی برچسب ها ابهام دارم.  

من تمام پکیج های مربوط به پیکره دکتر بیجن خان را از بخش دانلود سایت دانشگاه تهران (سایت زیر) دانلود کردم.
http://ece.ut.ac.ir/dbrg/bijankhan/
ولی در مورد برخی تگ ها چیزی پیدا نکردم.

ضمناً یک سوال دیگر داشتم که آیا برچسب زنی براساس تگ های پیکره ی دادگان هم در هضم امکان پذیر است؟

با تشکر

**Comment by nournia** [comment]
مقاله مربوط به پیکره دکتر بی‌جن‌خان این هست که البته توضیح زیادی در مورد برچسب‌ها ننوشته:

Bijankhan, Mahmood et al. “Lessons from Building a Persian Written Corpus: Peykare.” Language Resources and Evaluation 45 (2011): 143–164.

من هم مرجع بهتری نمی‌شناسم. البته در نسخه‌های بعدی هضم، از برچسب‌های جایگزین استفاده می‌کنیم، احتمالا اینها:

Petrov, Slav, Dipanjan Das, and Ryan McDonald. “A Universal Part-of-Speech Tagset.” Proceedings of LREC. N. p., 2012.

تعداد جمله‌های دادگان خیلی خیلی کمتر از پیکره دکتر بی‌جن‌خان هست و ما هم از این داده برای آموزش تجزیه‌گر وابستگی و تجزیه سطحی استفاده کردیم. در واقع آموزش برچسب‌زن صرفی روی اونها به دقت خوبی نمی‌رسه.

البته می‌تونید تبدیل برچسب‌های دادگان به برچسب‌های پیکره دکتر بی‌جن‌خان رو [در کدها](https://github.com/sobhe/hazm/blob/eea2b8a667bbdc7acaeaa5ac274e4fcd19c4fca2/hazm/DadeganReader.py#L18) ببینید.

**Comment by davoodmf** [comment]
خیلی ممنون از مقاله ای که معرفی کردید و اون بخش کد که لینک کردید
