### ISSUE TITLE
مشکل نصب نسخه 0.5 روی ویندوز

### ISSUE THREAD

**Issue by hosseinakbarian** [sobhe/hazm#42]
من برای استفاده از نسخه ی 0.5 با خطای 

AttributeError: 'module' object has no attribute wapiti

و برای استفاده از نسخه ی 0.4 با این خطا مواحه میشم

AttributeError: 'module' object has no attribute 'POSTagger'

**Comment by nournia** [comment]
<div dir=rtl>
سلام
متاسفانه نسخه 0.5 هضم روی ویندوز سخت نصب می‌شه. برای همین توصیه می‌کنم از لینوکس یا مک استفاده کنید.

ولی خب نسخه 0.4 روی ویندوز مشکلی نداره، می‌تونید با این دستور نصب کنید:

    pip install hazm==0.4 nltk==3.0.0 --upgrade

البته در این صورت باید از مدل‌های مخصوص این نسخه استفاده کنید:
https://github.com/sobhe/hazm/releases/download/v0.4/resources-0.4.zip

**Comment by mah110** [comment]
سلام
SyntaxError: invalid syntax خطای install رو که وارد می کنم از pip install hazm==0.4 nltk==3.0.0 --upgradeمن 
 خطا می گیره.installرو می گیره. از

**Comment by nournia** [comment]
<div dir=rtl>
شاید باید خط فرمان رو به پوشه نصب پایتون ببرید و بنویسید:

    python -m pip install hazm==0.4 nltk==3.0.0 --upgrade

البته این چیزها به هضم ربطی نداره

**Comment by mah110** [comment]
سلام
هضم رو باید از کجا دانلود کنم ؟برای نصب بر روی ویندوز7 می خوام .نسخه ی پایتونمم 3.3.5 و 3.4 است.
 رو سایت فقط نسخه لینوکسیش هست.این دستور بالا هم ماله لینوکسه.نسخه پایتون نصب شده روی ابونتوی32 من 2.7.هستش.اصلا این کد بالا رو پیدا نمی کنه.من فقط ریشه یاب و برچسب زن هضم رو می خوام.خواهشا لینک دانلود برای نسخه ویندوزیش رو جمیل کنید برام.در ضمن کدهاش رو هم که ران می کنم خطای گفته شده در کامنت اول رو میده.لطفا لطفا راهنمایی بفرمایید.

**Comment by nournia** [comment]
<div dir=rtl>
دستوری که نوشتم مربوط به ویندوز بود و گفتم که باید در پوشه نصب پایتون اجراش کنید
فایل نصب هضم قدیمی اینجاست:
https://pypi.python.org/packages/any/h/hazm/hazm-0.4.linux-x86_64.exe

**Comment by nournia** [comment]
<div dir=rtl>

[سایت هضم](http://www.sobhe.ir/hazm) برای آموزش نصب روی ویندوز به‌روز شد.

**Comment by mahboobnejati** [comment]
من نسخه ی 4 هضم را نصب کردم با NLTK 3.0.5
اما بازم ارور 
AttributeError: 'module' object has no attribute 'POSTagger'
را میده . مشکل چی هست ؟
سورس ها و مدل های 4 راهم بهش اضافه کردم

**Comment by nournia** [comment]
<div dir=rtl>
در لینوکس نیازی به نصب نسخه قبلی ندارید.

**Comment by mahboobnejati** [comment]
در نسخه ی جدیدش این خطا را میده برای postagger
TypeError: Can't instantiate abstract class POSTagger with abstract methods tag

**Comment by nournia** [comment]
<div dir=rtl>
با این دستور نصب می‌کنید؟

    pip install hazm --upgrade

**Comment by mahboobnejati** [comment]
نه فایلش را به پکیج ها اضافه میکنم . سیستم لینوکسم به نت متصل نیست

**Comment by nournia** [comment]
<div dir=rtl>
خب پس جستجو کنید که چطور بسته پایتون رو باید آفلاین نصب کرد.

**Comment by mahboobnejati** [comment]
خیلی خیلی خیلی ممنون
درست شد.

**Comment by nournia** [comment]
<div dir=rtl>

سلام
شاید با این دستور مشکل حل بشه:

     pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by aminzm** [comment]
سلام دوستان من میخوام هضم رو تو
wsl
نصب کنم این اختار رو میده
نسخه
pip
رو هم آپدیت کردم ولی بازم این اخطار رو داد:
Collecting hazm
  Using cached https://files.pythonhosted.org/packages/22/13/5a7074bc11d20dbbb46239349ac3f85f7edc148b4cf68e9b8c2f8263830c/hazm-0.7.0-py3-none-any.whl
Requirement already satisfied: nltk==3.3 in ./anaconda3/lib/python3.7/site-packages (from hazm) (3.3)
Collecting libwapiti>=0.2.1; platform_system != "Windows" (from hazm)
  Using cached https://files.pythonhosted.org/packages/bc/0f/1c9b49bb49821b5856a64ea6fac8d96a619b9f291d1f06999ea98a32c89c/libwapiti-0.2.1.tar.gz
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from nltk==3.3->hazm) (1.12.0)
Building wheels for collected packages: libwapiti
  Building wheel for libwapiti (setup.py) ... error
  ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z87050eq --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/wapiti
  copying wapiti/__init__.py -> build/lib.linux-x86_64-3.7/wapiti
  copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
  copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
  running egg_info
  writing libwapiti.egg-info/PKG-INFO
  writing dependency_links to libwapiti.egg-info/dependency_links.txt
  writing requirements to libwapiti.egg-info/requires.txt
  writing top-level names to libwapiti.egg-info/top_level.txt
  reading manifest file 'libwapiti.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'libwapiti.egg-info/SOURCES.txt'
  running build_ext
  building 'libwapiti' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/cwapiti
  creating build/temp.linux-x86_64-3.7/cwapiti/src
  creating build/temp.linux-x86_64-3.7/libwapiti
  creating build/temp.linux-x86_64-3.7/libwapiti/src
  gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for libwapiti
  Running setup.py clean for libwapiti
Failed to build libwapiti
Installing collected packages: libwapiti, hazm
  Running setup.py install for libwapiti ... error
    ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/wapiti
    copying wapiti/__init__.py -> build/lib.linux-x86_64-3.7/wapiti
    copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
    copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
    running egg_info
    writing libwapiti.egg-info/PKG-INFO
    writing dependency_links to libwapiti.egg-info/dependency_links.txt
    writing requirements to libwapiti.egg-info/requires.txt
    writing top-level names to libwapiti.egg-info/top_level.txt
    reading manifest file 'libwapiti.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'libwapiti.egg-info/SOURCES.txt'
    running build_ext
    building 'libwapiti' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cwapiti
    creating build/temp.linux-x86_64-3.7/cwapiti/src
    creating build/temp.linux-x86_64-3.7/libwapiti
    creating build/temp.linux-x86_64-3.7/libwapiti/src
    gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-vecnwror/libwapiti/

**Comment by Akbar30Bill** [comment]
> ## سلام دوستان من میخوام هضم رو تو
> wsl
> نصب کنم این اختار رو میده
> نسخه
> pip
> رو هم آپدیت کردم ولی بازم این اخطار رو داد:
> Collecting hazm
> Using cached https://files.pythonhosted.org/packages/22/13/5a7074bc11d20dbbb46239349ac3f85f7edc148b4cf68e9b8c2f8263830c/hazm-0.7.0-py3-none-any.whl
> Requirement already satisfied: nltk==3.3 in ./anaconda3/lib/python3.7/site-packages (from hazm) (3.3)
> Collecting libwapiti>=0.2.1; platform_system != "Windows" (from hazm)
> Using cached https://files.pythonhosted.org/packages/bc/0f/1c9b49bb49821b5856a64ea6fac8d96a619b9f291d1f06999ea98a32c89c/libwapiti-0.2.1.tar.gz
> Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from nltk==3.3->hazm) (1.12.0)
> Building wheels for collected packages: libwapiti
> Building wheel for libwapiti (setup.py) ... error
> ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z87050eq --python-tag cp37:
> ERROR: running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/**init**.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
> running egg_info
> writing libwapiti.egg-info/PKG-INFO
> writing dependency_links to libwapiti.egg-info/dependency_links.txt
> writing requirements to libwapiti.egg-info/requires.txt
> writing top-level names to libwapiti.egg-info/top_level.txt
> reading manifest file 'libwapiti.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'libwapiti.egg-info/SOURCES.txt'
> running build_ext
> building 'libwapiti' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cwapiti
> creating build/temp.linux-x86_64-3.7/cwapiti/src
> creating build/temp.linux-x86_64-3.7/libwapiti
> creating build/temp.linux-x86_64-3.7/libwapiti/src
> gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
> unable to execute 'gcc': No such file or directory
> error: command 'gcc' failed with exit status 1
> ERROR: Failed building wheel for libwapiti
> Running setup.py clean for libwapiti
> Failed to build libwapiti
> Installing collected packages: libwapiti, hazm
> Running setup.py install for libwapiti ... error
> ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile:
> ERROR: running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/**init**.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
> running egg_info
> writing libwapiti.egg-info/PKG-INFO
> writing dependency_links to libwapiti.egg-info/dependency_links.txt
> writing requirements to libwapiti.egg-info/requires.txt
> writing top-level names to libwapiti.egg-info/top_level.txt
> reading manifest file 'libwapiti.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'libwapiti.egg-info/SOURCES.txt'
> running build_ext
> building 'libwapiti' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cwapiti
> creating build/temp.linux-x86_64-3.7/cwapiti/src
> creating build/temp.linux-x86_64-3.7/libwapiti
> creating build/temp.linux-x86_64-3.7/libwapiti/src
> gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
> unable to execute 'gcc': No such file or directory
> error: command 'gcc' failed with exit status 1
> ----------------------------------------
> ERROR: Command "/home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-vecnwror/libwapiti/

```bash
sudo apt install build-essential
```
مشکل رو حل میکنه ؟

**Comment by NeginAbadani** [comment]
> ## سلام دوستان من میخوام هضم رو تو
> wsl
> نصب کنم این اختار رو میده
> نسخه
> pip
> رو هم آپدیت کردم ولی بازم این اخطار رو داد:
> Collecting hazm
> Using cached https://files.pythonhosted.org/packages/22/13/5a7074bc11d20dbbb46239349ac3f85f7edc148b4cf68e9b8c2f8263830c/hazm-0.7.0-py3-none-any.whl
> Requirement already satisfied: nltk==3.3 in ./anaconda3/lib/python3.7/site-packages (from hazm) (3.3)
> Collecting libwapiti>=0.2.1; platform_system != "Windows" (from hazm)
> Using cached https://files.pythonhosted.org/packages/bc/0f/1c9b49bb49821b5856a64ea6fac8d96a619b9f291d1f06999ea98a32c89c/libwapiti-0.2.1.tar.gz
> Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from nltk==3.3->hazm) (1.12.0)
> Building wheels for collected packages: libwapiti
> Building wheel for libwapiti (setup.py) ... error
> ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z87050eq --python-tag cp37:
> ERROR: running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/**init**.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
> running egg_info
> writing libwapiti.egg-info/PKG-INFO
> writing dependency_links to libwapiti.egg-info/dependency_links.txt
> writing requirements to libwapiti.egg-info/requires.txt
> writing top-level names to libwapiti.egg-info/top_level.txt
> reading manifest file 'libwapiti.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'libwapiti.egg-info/SOURCES.txt'
> running build_ext
> building 'libwapiti' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cwapiti
> creating build/temp.linux-x86_64-3.7/cwapiti/src
> creating build/temp.linux-x86_64-3.7/libwapiti
> creating build/temp.linux-x86_64-3.7/libwapiti/src
> gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
> unable to execute 'gcc': No such file or directory
> error: command 'gcc' failed with exit status 1
> ERROR: Failed building wheel for libwapiti
> Running setup.py clean for libwapiti
> Failed to build libwapiti
> Installing collected packages: libwapiti, hazm
> Running setup.py install for libwapiti ... error
> ERROR: Complete output from command /home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile:
> ERROR: running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/**init**.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/api.py -> build/lib.linux-x86_64-3.7/wapiti
> copying wapiti/script.py -> build/lib.linux-x86_64-3.7/wapiti
> running egg_info
> writing libwapiti.egg-info/PKG-INFO
> writing dependency_links to libwapiti.egg-info/dependency_links.txt
> writing requirements to libwapiti.egg-info/requires.txt
> writing top-level names to libwapiti.egg-info/top_level.txt
> reading manifest file 'libwapiti.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'libwapiti.egg-info/SOURCES.txt'
> running build_ext
> building 'libwapiti' extension
> creating build/temp.linux-x86_64-3.7
> creating build/temp.linux-x86_64-3.7/cwapiti
> creating build/temp.linux-x86_64-3.7/cwapiti/src
> creating build/temp.linux-x86_64-3.7/libwapiti
> creating build/temp.linux-x86_64-3.7/libwapiti/src
> gcc -pthread -B /home/amin/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icwapiti/src -Ilibwapiti -I/home/amin/anaconda3/include/python3.7m -c cwapiti/src/bcd.c -o build/temp.linux-x86_64-3.7/cwapiti/src/bcd.o -std=c99
> unable to execute 'gcc': No such file or directory
> error: command 'gcc' failed with exit status 1
> ----------------------------------------
> ERROR: Command "/home/amin/anaconda3/bin/python -u -c 'import setuptools, tokenize;**file**='"'"'/tmp/pip-install-vecnwror/libwapiti/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-csdn3gdk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-vecnwror/libwapiti/

من هم همین مشکل رو دارم روی ویندوز
