### ISSUE TITLE
chunker

### ISSUE THREAD

**Issue by djcesb** [sobhe/hazm#43]
سلام
همونطور که توی راهنمای استفاده از برنامه هضم(کد پایتون) در سایت قرار دادید قسمتی تحت عنوان چانکر وجود داره
آیا چانکر در برنامه ان.هضم(کد سی شارپ) هم وجود داره؟؟
اگر وجود داره لطفا راهنمایی کنید چطور میشه ازش استفاده کرد
ممنون

**Comment by mojtaba-khallash** [comment]
سلام
نه در نسخه سی شارپ این امکان وجود ندارد
نسخه سی شارپ معادل نسخه 0.1 کد پایتون هضم هست که در آن نسخه چانکر وجود نداشت

**Comment by leila-net** [comment]
سلام دوستان 

هنوز این مورد در nhazm رفع نشده ؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خیر. برای این منظور می‌تونید از نسخه پایتونی استفاده کنید و مثلا در کد سی‌شارپ اون رو به صورت برنامه خارجی اجرا کنید.
