### ISSUE TITLE
 persian.tagger فایل

### ISSUE THREAD

**Issue by ashkankhatir** [sobhe/hazm#44]
سلام، خسته نباشی بابت کاری که کردین. من برنامه هضم را برای زبان سی شارپ که میخواستم استفاده کنم، برنامه گفت فایل "پرشیین تگر" را نداره. بررسی که کردم فایل بود ولی خالی. پیام اکسپشن کی داد به شرح زیر بود 
Unrecoverable error while loading a tagger model 

سوال بعدی اینکه در سی شارپ چطور عبارات اسمی و فعلی را میشه تشخیص داد ؟

تشکر

**Comment by nournia** [comment]
<div dir=rtl>
سلام
کد سی‌شارپ تبدیل شده نسخه قدیمی هضم هست #43 و امکان تشخیص عبارات رو نداره
فایلی که دنبالش هستید رو [اینجا](https://github.com/sobhe/hazm/releases/download/v0.5/resources-stanford.zip) پیدا کنید.
