### ISSUE TITLE
POStagger

### ISSUE THREAD

**Issue by mah110** [sobhe/hazm#45]
سلام
 هضم شما نیاز دارم.من در محیط پایتون 3.4 و 3.3.5 در ویندوز 7 کار میکنم.هر چه تو سایت گشتم POStaggerمن برای پایان نامه ام به 
 دانلود و نصب کنم.خواهش می کنم منو راهنمایی بفرمایید.من برای پایان نامه ام به ریشه یاب و برچسب زن طراحی nltkرو مثل hazmنتونستم 
شده ی شما به زبان پایتون نیاز دارم.چطور باید دانلود و نصبش کنم.

**Comment by nournia** [comment]
لطفا نگاه به #42 بندازید
