### ISSUE TITLE
wapiti

### ISSUE THREAD

**Issue by mah110** [sobhe/hazm#47]
رو در پایتون 3.3.5 و ویندوز7 نصب کنم؟ wapitiسلام.ببخشید من چطور

**Comment by nournia** [comment]
<div dir=rtl>
همونطور که گفته شد #42 نصب وپیتی روی ویندوز سخته، برای این کار باید از [Cygwin](https://www.cygwin.com) استفاده کنید. اگر متخصص نیستید توصیه نمی‌کنم.
استفاده در لینوکس خیلی آسون‌تره.

**Comment by mah110** [comment]
خوب من چیکار کنم؟ برای پایان نامه ام POStagger رو می خوام.چطور تو
پایتون3.3.5 در محیط ویندوز7 ازش استفاده کنم؟
اگه ممکنه یه شماره بدین من تماس بگیرم و تلفنی مشکلم رو خدمتتون بگم.

2015-08-08 14:11 GMT+04:30 Alireza Nourian <notifications@github.com>:

**Comment by nournia** [comment]
می‌تونید از واسط وب هضم استفاده کنید:
http://www.sobhe.ir/hazm/demo/

اگر مشکل‌تون به هضم ربطی نداره، می‌تونید به ایمیل شخصی من بنویسید

**Comment by mah110** [comment]
مشکل من استفاده از کد POStagger. که وقتی در کنارش SequenceTagger رو هم اجرا
می کنم، خطا میده که ماژول wapiti نصب نیست.

2015-08-08 21:07 GMT+04:30 Alireza Nourian <notifications@github.com>:

**Comment by mah110** [comment]
سلام
ببخشید بنظر شما میشه برای دستور زبان فارسی الگوریتمی مثل همین برچسب زن شما
پیاده سازی کرد که با توجه به اجزای جمله مثل صفت ، فعل، اسم و... تشخیص بده
جمله منفی شده است یا نه؟ چون از دیدگاه من باید حجم زیادی از تمام منفی کننده
ها اعم از منفی کننده های فعلی، منفی کننده ی اسم ، صفت و.... را پیدا کرد و
به الگوریتم داد. حتی بعضا وجود خود حروف اضافه نقش منفی کننده فعل را بازی می
کنند. مثلا جمله" من در مقابل بی عدالتی برنمی تابم." این جمله مخالف بی
عدالتی ست و با عدالت موافق است.آیا تحت الگوریتمی می توان این تشخیص را در
این جمله یا جمله های بسیار پیچیده تر از این تشخیص داد؟ بنظر من این کار در
حوزه ی زبان فارسی بعلت دامنه وسیع ادبی اش تقریبا امکان پذیر نیست. بخصوص
زمانی که جمله سوالی ست یا دیگر جملات.نظر شما چیست؟لطفا پاسخ دهید.یا مثلا
جمله ی"بنظر من حجاب فقط در محیط خانه خوب است." این جمله در واقع مخالف حجاب
است ولی پردازش آن بر اساس اجزای جمله چگونه باید باشد؟
بسیار سپاسگذارم.....

2015-08-08 21:11 GMT+04:30 ahya hashemi <ah.ah7918@gmail.com>:

**Comment by nournia** [comment]
<div dir=rtl>
برای انجام این کار سعی می‌کنن به ماشین آموزش بدن که چه جمله‌هایی منفی هستن. در واقع لازم نیست فهرست طولانی از واژه‌ها پیدا کنید، کافیه که مجموعه‌ای از جمله‌ها داشته باشید که مشخص باشه کدوم‌ها منفی هستن و بعد اونها رو به خوبی به ماشین یاد بدید.

در زبانی فارسی، [این پیکره](http://dadegan.ir/catalog/sentipers) رو برای همین منظور آماده کردن
این هم یک روش بسیار کارا برای آموزش به ماشین:
http://nlp.stanford.edu/sentiment

**Comment by mahboobnejati** [comment]
من الان روی لینوکس که نصب کردم نسخه جدید را بعد از ارور
TypeError: Can't instantiate abstract class POSTagger with abstract methods tag
حالا ارور 
no module named wapiti 
 میده 
الان باید چکار کنم ؟
خواهش میکنم یک جواب درست به بنده بدهید.
