### ISSUE TITLE
خروجی پارسر وابستگی

### ISSUE THREAD

**Issue by ariana2011** [sobhe/hazm#48]
با سلام و خسته نباشید،
سوالی از خدمتتون داشتم. در قسمت تحلیل وابستگی از نمادهایی برای برچسب‌های نحوی استفاده شده که معنای آن‌ها را پیدا نکردم و در سورس هم کاتالوگی که نشانگر معنای هر کدام از این برچسب‌ها باشد نیافتم. آیا امکانش هست که در این مورد راهنمایی بفرمایید؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
برچسب‌های وابستگی همه از پیکره دادگان اومدن که می‌تونید توضیح‌شون رو می‌تونید در مقاله داده‌ها پیدا کنید:
http://aclweb.org/anthology/N/N13/N13-1031v2.pdf

**Comment by ariana2011** [comment]
سپاسگزارم

**Comment by ariana2011** [comment]
سوال دیگری هم داشتم. همونطور که تو مقاله اومده دو نوع برخورد با «را» صورت گرفته که در یک نوع هستهٔ «را» فعل هست و در نوع دیگه «را» جزوی از گروه اسمی به حساب آمده.(مثلا در جمله: کتابی را که گفتی خواندم). هضم نوع اول را خروجی می‌دهد. راهی هست که بتونم به صورت دوم خروجی بگیرم؟

**Comment by nournia** [comment]
<div dir=rtl>
درست می‌فرمایید، ما در هضم، نوع اول رو آموزش دادیم به تجزیه‌گر.
تبدیل این دو نوع به همدیگه ساده است و با چند خط کد قابل انجامه.
اگر براتون مهمه، از [آقای رسولی](http://www.cs.columbia.edu/~rasooli/) بخواید راهنمایی‌تون کنن.

**Comment by ariana2011** [comment]
با سلام و تشکر. 
چون سوالاتم مربوط به خروجی پارسر وابستگی است همینجا مطرح می کنم. 
چطور می تونم خروجی پارسر وابستگی رو به صورت لیست، دیکشنری یا تاپل داشته باشم؟ به صورت عادی خروجی یه آبجکت NLTKهست که iterable نیست. ساده‌ترین راهی که به نظرم رسید تبدیل خروجی به string هست و سپس تبدیل به لیست و غیره. اما در مورد یکی از موارد خروجی که dep هست، کار تمیز و دلخواه نمی‌شه. مخصوصا در مواردی که چند وابسته در dep باشند یا در مواردی مثل مورد زیر:
 'deps': defaultdict(<class 'list'>, {'POSDEP': [27]})

**Comment by ariana2011** [comment]
متاسفانه هر کاری میکنم نوشته‌ها از راست به چپ نمی‌شن. امیدوارم سوالم قابل خوندن باشه.

**Comment by nournia** [comment]
<div dir=rtl>
شاید استفاده از `tree.nodes` کمک‌تون بکنه. این ویژگی شامل فهرست واژه‌ها و یال‌هاست.
راه دیگه هم تبدیل درخت به حالت conll هست:
</div>

    tree.to_conll(10)
