### ISSUE TITLE
لیست کلمات بازدارنده (Stop words)

### ISSUE THREAD

**Issue by hosseinip** [sobhe/hazm#50]
با سلام
به نظرم اضافه کردن لیست کلمات بازدارنده و فیلتر کردن این کلمات در قسمت پیش پردازش متون میتونه خیلی خوب باشه
با اینکه شاید کار خیلی چالشی نباشه ولی خب در اکثر پردازشها و آماده سازی مجموعه داده های آموزشی میتونه مورد استفاده قرار بگیره

**Comment by nournia** [comment]
<div dir=rtl>
سلام
به امید خدا این کار رو می‌کنیم؛ احتمالا در نسخه بعدی
