### ISSUE TITLE
تگ های pos tagger

### ISSUE THREAD

**Issue by hosseinakbarian** [sobhe/hazm#51]
با سلام و عرض ادب میخواستم بدونم تگ های 
Ne,AJe,DET

نشان دهنده ی چه دسته کلماتی هستند و همچنین این که نسخه ی جاوای پکیجتون تا چه حد مطابق نسخه ی پایتون آپدیت شده

**Comment by nournia** [comment]
<div dir=rtl>
سلام
برای توضیح برچسب‌ها این بخش رو ببنید: #41 
حرف e در پایان برچسب نشون می‌ده که این واژه کسره اضافه داره
این ویژگی به تجزیه سطحی و تجزیه وابستگی کمک می‌کنه:
[On the Importance of Ezafe Construction in Persian Parsing](http://anthology.aclweb.org/P/P15/P15-2.pdf#page=905)

در مورد نسخه جاوا هم باید بگم که این نسخه همگام با نسخه اصلی پیش نمی‌ره و اگر سوالی دارید فکر کنم در همون پروژه بپرسید، راهنمایی‌تون کنن
