### ISSUE TITLE
چسباندن «های» به کلمه

### ISSUE THREAD

**Issue by metemaddar** [sobhe/hazm#53]
برام جالب بود که پیرایشگرهای نیم‌فاصله سراغ «های» نمی‌رفتند.
و جالب‌تر اینجا بود که هضم هم هنوز به سراغشون نرفته‌بود.
چه مشکلی وجود داره که «های» رو جدا نکردیم؟

**Comment by nournia** [comment]
<div dir=rtl>
هضم این کار رو انجام می‌ده. می‌خواید در صفحه دمو تست کنید:
http://www.sobhe.ir/hazm/demo/
