### ISSUE TITLE
استخراج اخبار همشهری

### ISSUE THREAD

**Issue by kzcom** [sobhe/hazm#54]
با سلام
چطور می توان خبرهای یک روز خاص همشهری را استخراج کنیم؟
( مثلا" متن اخبار روز1997/05/25 )
String year="1997";
String month="05";
String day="25";
String news="all texts in that day using hamshahriReader.cs..."

**Comment by nournia** [comment]
<div dir=rtl>
سلام
می‌تونید همه اسناد رو بخونید و اونهایی که برای یک روز خاص هست رو بردارید.
البته هضم رو از سورس نصب کنید، چون تاریخ اسناد پیکره همشهری رو تازه [ اضافه کردم](https://github.com/sobhe/hazm/commit/4022618d4ff00b759240366ac48106da27778e31)
