### ISSUE TITLE
گروه ها

### ISSUE THREAD

**Issue by mitra8814** [sobhe/hazm#55]
سلام
برای جمله ی زیر
کارگردان رومی فیلم مونیخ کیست؟
کد هضم در لینوکس، به صورت زیر گروه بندی می کند
کارگردان رومی فیلم NP
مونیخ کیست؟VP
در حالی که فکر کنم درستش اینه:
کارگردان رومی فیلم مونیخ NP
کیست VP

درسته؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
پاسخ هضم برای این جمله:
[کارگردان رومی NP] [فیلم مونیخ NP] [کیست VP] ؟

در حالی که درستش اینه (همونطور که گفتید):
[کارگردان رومی فیلم مونیخ NP] [کیست VP] ؟
