### ISSUE TITLE
مشکل در نمایش نتیجه پارسر

### ISSUE THREAD

**Issue by h-shariati** [sobhe/hazm#57]
هنگام اجرای کد زیر خطای بعدی نمایش داده می شود
`def api_article(Matn):
    a= Matn.replace('_',' ')
    return jsonify({'devices': parser.parse(word_tokenize(a)).tree().pprint()})`

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)`

debug
File "/usr/local/lib/python2.7/dist-packages/hazm_test.py", line 55, in api_article
return jsonify({'devices': parser.parse(word_tokenize(ss)).tree().pprint()})
File "/usr/local/lib/python2.7/dist-packages/nltk/tree.py", line 748, in pprint
print(self.pformat(**kwargs), file=stream)

**Comment by nournia** [comment]
بالای کدتون این رو بنویسید، شاید درست بشه:

    from __future__ import unicode_literals
