### ISSUE TITLE
What is the tagset used for the POS tagger?

### ISSUE THREAD

**Issue by miracle2k** [sobhe/hazm#58]
May be it should be obvious - I'm a complete NLP beginner.

**Comment by nournia** [comment]
We used Peykare corpus for training POS tagger. You can find out about its tagest in their published paper:

    Bijankhan, M., Sheykhzadegan, J., Bahrani, M., & Ghayoomi, M. (2011). Lessons from building a Persian written corpus: Peykare. Language Resources and Evaluation, 45, 143–164.
