### ISSUE TITLE
نحوه آموروش POS tagger

### ISSUE THREAD

**Issue by naeimrezaeian** [sobhe/hazm#61]
سلام 
میشه یک مقدار در مورد اون فایل مدلی که در این سیستم استفاده کرده اید توضحی بدهید  
این سیستم یادگیری ماشینی از چه الگوریتمی استفاده شده و آیا این امکان هست که این آموزش را برای یک زبان دیگری انجام داد و برای ساهت این مدل اختیاج به چه چیزی می باشد 
و روش ارزیابی که این سیستم با چه دقتی کار میکند به چه گونه میباشد 
با تشکر

**Comment by nournia** [comment]
<div dir=rtl>
سلام
مدل مورد استفاده برای تحلیل صرفی اسمش هست CRF که خب نیاز به مطالعه داره.
برای زبان‌های دیگه هم میشه این کار رو انجام داد ولی نیاز به داده هست، یعنی تعداد زیادی جمله که انسان مشخص کرده باشه هر واژه در اونها چه نقشی داره.
برای ارزیابی هم بخشی از داده‌ها رو آموزش ندادیم تا در زمان ارزیابی، با کمک اونها دقت رو بسنجیم.

**Comment by naeimrezaeian** [comment]
ممنون از پاسخ شما 
شما خودتون crf را پیاده سازی کرده اید ؟ و در این پروژه استفاده شده 
در سورس کد برنامه از کتابخانه StanfordPOSTagger استفاده شده میشه راهنمایی بفرماید از این چه استفاده ای می شود ؟
و سوال اخر برای این قسمت یک فایل persian.tagger هست خواستم بپرسم این فایل را در چه برنامه ای ساخته شده است ؟

با تشکر از شما

**Comment by nournia** [comment]
<div dir=rtl>
برای CRF از [Wapiti](http://wapiti.limsi.fr) استفاده کردیم.
در نسخه قبل، از ابزار استنفورد استفاده می‌کردیم
فایلی هم که گفتید مربوط به همون ابزار تگر استنفورد هست و نسخه قدیمی هضم از اون استفاده می‌کرد.

**Comment by naeimrezaeian** [comment]
این نسخه از هضم که از ابزار Wapiti  استفاده کرده اید را از کجا میشه دانلود کرد ؟

**Comment by naeimrezaeian** [comment]
میشه راهنمایی بفرمایید نسخه جدید برنامه را از کجا باید دانلود کنیم
