### ISSUE TITLE
جدا کردن کلمات کلیدی متن

### ISSUE THREAD

**Issue by boogardgodig** [sobhe/hazm#62]
سلام 
من می خوام کلمات کلیدی صفحات وب رو جدا کنم. تابعی دارید که بگه فرکانس هر کدوم از واژه ها توی متون فارسی چقدره؟
یا روش دیگه یی برای این کار می تونید معرفی کنید؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
مطلب [این صفحه](http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html) کمک می‌کنه کاری که می‌خواید رو انجام بدید.
تنها کمک هضم در این کار، تقطیع کلمات هست.
