### ISSUE TITLE
سوال در مورد جداسازی تکواژها

### ISSUE THREAD

**Issue by Nimda1482** [sobhe/hazm#65]
درود آیا امکانش هست که با هضم تکواژهای کلمات موجود در جملات رو جدا کنیم؟

**Comment by nournia** [comment]
<div dir=rtl>
سلام
نه این کار رو بلد نیست.

**Comment by Nimda1482** [comment]
در هیچ حالتی ممکن نیست ؟ نمیشه مدلش رو بهش داد تا این کار رو انجام بده ؟

**Comment by nournia** [comment]
<div dir=rtl>
خب، باید داده داشته باشیم.
یعنی مجموعه‌ای از واژه‌ها رو نیاز داریم که به تکواژها شکسته شدن.
ممکنه در داده فارس‌نت این اطلاعات موجود باشه.
