### ISSUE TITLE
مشکل در ریشه یابی و کدینگ 

### ISSUE THREAD

**Issue by mahmoud831** [sobhe/hazm#66]
from **future** import unicode_literals
from hazm import *
infile = open('D:\f5.txt', 'r')
outfile = open('D:\f2.txt', 'w')
sent = []
word = []
for line in infile:
    sent = sent_tokenize(line)
    words = word_tokenize(sent)
    for w in words:
            lemmatizer = Lemmatizer()
            print(lemmatizer.lemmatize(w))
            #outfile.write(lemmatizer.lemmatize(w)+' ')

```
outfile.write('\n')
```

infile.close()
outfile.close()

این کد این خطا رو میده:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 0: ordinal not in range(128)
لطفا راهنمایی بفرمائید

**Comment by nournia** [comment]
برای نوشتن یونیکد باید فایل رو به این شکل باز کنید:

	from future import unicode_literals, print_function
	import codecs
	from hazm import *
	infile = open('D:\f5.txt', 'r')
	outfile = codecs.open('D:\f2.txt', 'w', 'utf8')
	sent = []
	word = []
	for line in infile:
		sent = sent_tokenize(line)
		words = word_tokenize(sent[0])
	for w in words:
		lemmatizer = Lemmatizer()
		print(lemmatizer.lemmatize(w)+' ', file=outfile)

در بخش تقطیع هم کد شما یک مشکل کوچیک داشت که درست کردم.

**Comment by mahmoud831** [comment]
![image](https://cloud.githubusercontent.com/assets/20658499/17136368/84e660c0-533d-11e6-8234-2afef3d9ddb7.png)
![image](https://cloud.githubusercontent.com/assets/20658499/17136377/9028ad26-533d-11e6-9049-6d34702d0f52.png)


در کمال تعجب مشکل حل نشد!!!!

**Comment by nournia** [comment]
<div dir=rtl>
فایل ورودی رو هم با `codecs` بخونید.
قطعه کد رو اصلاح کردم.

**Comment by mahmoud831** [comment]
بسیار ممنونم.
