### ISSUE TITLE
نصب hazm

### ISSUE THREAD

**Issue by fatemeshojaei** [sobhe/hazm#71]
سلام این فایل
 resources4.0 و 
hazm-master 
که دانلود کردیم باید چجوری نصب کنیم؟

**Comment by nournia** [comment]
سلام

https://github.com/sobhe/hazm/releases/download/v0.4/resources-0.4.zip
https://github.com/sobhe/hazm/archive/master.zip

**Comment by fatemeshojaei** [comment]
خب اینارو دانلود کردم چحوری باید رو اناکوندا نصب کرد و ازشون استفاده کرد؟

**Comment by nournia** [comment]
<div dir=rtl>
خب، جواب این سوال یه‌مقدار پایتونی هست.
اول باید محیط آناکوندا رو فعال کنید.
بعد با استفاده `pip` بسته رو نصب کنید و فایل‌های پوشه `resources` رو در جای مناسب قرار بدید.

**Comment by fatemeshojaei** [comment]
میشه دستور نصبشو بزارین

**Comment by fatemeshojaei** [comment]
یک سایت یا یم منبع برای یادگیری تحلیل متون فارسی در وب 
و یادگیری هضم میشه معرفی کنین؟

**Comment by hatamiarash7** [comment]
تو پوشه کتابخانه برید و 
python setup.py install
رو اجرا کنید برای نصب

فایل منابع هم که تو پوشه خودش قرار بدید

**Comment by RosieTaj** [comment]
سلام
من فایل ریسورس را دانلود کردم ولی نمیدونم وقتی میگید در مسیر پروژه قرار بدبد یعنی کجا باید کپی کنم. هرجا کپی میکنم نمیتونم تگر و پارسر را فعال کنم. من در پیدا کردن مسیرها مشکل دارم. میتونید من را راهنمایی کنید.ممنون در سیستم مک و هم اوبونتو امتحان کردم ولی نشد

**Comment by nournia** [comment]
<div dir=rtl>

سلام
فرض کنید یک فایل پایتون دارید. دقیقا کنارش پوشه رو اکسترکت کنید. این‌طوری یک فایل پایتون دارید و کنارش پوشه resources قرار گرفته.

**Comment by RosieTaj** [comment]
سلام آقای نوریان وقتتون بخیر
خیلی ممنونم که پاسخم را دادید. فردا ارائه سمینار دارم درمورد tagger.
روشی که گفتین را انجام میدم. نتیجه را به شما اطلاع میدم.

**Comment by RosieTaj** [comment]
سلام مجدد
آقای نوریان درست شد. خیلی خیلی سپاسگزارم.
