### ISSUE TITLE
استخراج رویدادها از متن

### ISSUE THREAD

**Issue by fardi123** [sobhe/hazm#72]
درخواستی که دارم اینه که بنده رو راهنمیایی کنید. من می خواهم متن را تحلیل کنم و رویدادهای بیان شده در متن را شناسایی و استخراج کنم. برنامه هزم تا چه حدی روی این کار کرده؟؟ خواهشا کمک کنید

**Comment by nournia** [comment]
<div dir=rtl>
سلام
هضم ابزار پایه پردازش زبان طبیعی هست. استخراج رویداد اما یک مساله هست که برای حلش به ابزارهایی مثل تجزیه سطحی و یا تجزیه نحوی نیاز دارید و اونها رو می‌تونید در هضم پیدا کنید.

شاید بد نباشه نگاهی هم به [باز](https://github.com/sobhe/baaz) بندازید.

**Comment by fardi123** [comment]
ممنون از پاسختون. میشه لطف کنید کدهای مربوط به تجزیه نحوی و سطحی را بهم بدید؟ چون تو هزم نمی دونم کدومش مربوط به تجزیه نحوی یا سطحی است. و اینکه این کد ها رو کپی کنم پایتون اجرا می شن یا بایستی ابزاری را نصب کنم؟ اگه به خود کد دسترسی پیدا کنم و طرز کارش رو ببینم کمک خیلی بزرگی بهم خواهد کرد. بی نهایت ممنون می شوم. امیدوارم کمک کنید بدجوری تو پایاننامم گیر کردم.fardi1001@gmail.com

**Comment by fardi123** [comment]
سلام. واقعیتش من رشتم نرم افزار هست و از هوش مصنوعی کم می دونم، اما
پایاننامم مرتبط با هوش مصنوعی و پردازش زبان طبیعی هست و عنوانش هم تصویب شده
نمی تونم عوض کنم، از آنجایی که هزم در رابطه با تجزیه نحوی و سطحی متن کار
کرده جای خوشحالی است، اگه شما می تونید در رابطه با عنوان پایاننامم کمک کنید
و به پایان برسه جبران خواهم کرد، یا اگر آشنایی دارید که بتونه این کار را
انجام بده، ممنون می شوم معرفی کنید، هزینشو تقدیم خواهم کرد. عنوان
پایاننامم( شناسایی و استخراج رویداداها به طور ساخت یافته(فاعل، مفعول، قید
مکان ، قید زمان) از داخل متون تخصصی فارسی با استفاده از تجزیه نحوی.) خواهشا
جواب بدید چون فرصت کم دارم

2016-09-25 19:58 GMT+03:30 Alireza Nourian <notifications@github.com>:

**Comment by nournia** [comment]
<div dir=rtl>
همه کدهای هضم در همین سایت قرار داده شده و طریقه نصب هم  در سایت مشخص هست.
فکر کنم برای استفاده باید کمی با پایتون آشنا بشید.

**Comment by fardi123** [comment]
ممنونم از راهنماییتون، واقعا لطف کردید.

2016-09-26 9:53 GMT+03:30 Alireza Nourian <notifications@github.com>:

**Comment by fardi123** [comment]
وقتی می خوام آناکوندا رو نصب کنم خطی میده... error launching instaler رو
میده. میشه راهنمایی کنید؟ قبلا نسخه 3.5 پایتون رو سیستمم نصب هست. برای نصب
کتابخانه هزم اول باید آناکوندا رو نصب کنم؟


2016-09-26 11:49 GMT+03:30 Fardzad Fardi <fardi1001@gmail.com>:

**Comment by nournia** [comment]
<div dir=rtl>
برای نصب هضم در ویندوز لطفا نگاهی به #42  بندازید.

**Comment by nournia** [comment]
<div dir=rtl>

[سایت هضم](http://www.sobhe.ir/hazm) برای آموزش نصب روی ویندوز به‌روز شد.

**Comment by fardi123** [comment]
سلام . ممنون از لطفتون
