### ISSUE TITLE
هجا کردن کلمات

### ISSUE THREAD

**Issue by Nimda1482** [sobhe/hazm#76]
درود آیا با استفاده از کتابخانه hazm امکان تقطیع کلمات در سطح هجا وجود دارد؟
اگر بله به چه صورتی؟اگر خیر راه دیگری برای انجام این عمل وجود دارد.

**Comment by nournia** [comment]
<div dir=rtl>
هضم این امکان رو نداره.
فکر می‌کنم مجموعه داده فارس‌نت بتونه به شما در این زمینه کمک بکنه.
البته من خودم استفاده نکردم و از روی توضیحات تهیه‌کننده‌ش این حرف رو می‌زنم.

**Comment by mvpcom** [comment]
@Nimda1482 سلام شما راهی برای هجا کردن پیدا کردی آخر؟
