### ISSUE TITLE
دسترسی داینامیک به لیست واژگان

### ISSUE THREAD

**Issue by ahangarha** [sobhe/hazm#78]
<div dir='rtl' align='right'>
سلام

آیا راهکاری وجود دارد که بتوان به طور مستقیم به لیست کلمات (مثل ایست‌واژه‌ها) دسترسی داشت؟ و یا اینکه حتی از طریق یک متود، ایست‌واژه‌ها رو از متن حذف کرد؟
چنین تابعی رو در بخشی از کدها دیدم. اما به دلیلی که نمی‌دونم، ظاهرا از پروژه حذف شده.

من الان به طور دستی فایل‌ها رو می‌خونم و تبدیل به آرایه می‌کنم. آیا راه به‌تری در این پروژه برای این کار تعبیه شده؟
</div>

**Comment by nournia** [comment]
برای رسیدن به فهرست واژه‌های مورد نظر از این تابع استفاده کنید:

    from hazm import stopwords
    stopwords.words()

برای تبدیل متن به واژه‌ها و حذف واژه‌های ایست می‌تونید از این کد استفاده کنید:

    from hazm import word_tokenize, sent_tokenize
    stops = set(stopwords.words())
    words = [[word for word in word_tokenize(sentence) if word not in stops] for sentence in sent_tokenize(text)]

**Comment by ahangarha** [comment]
ممنونم

اما ظاهرا چنین امکانی برای دسترسی به لیست واژگان تایید شده که در فایل دیگری نگه‌داری می‌شود وجود نداشته باشد
منظورم
words.dat
هست

درست می‌گم؟

**Comment by nournia** [comment]
این‌طوری می‌تونید:

    from hazm import Lemmatizer
    lemmatizer = Lemmatizer()
    lemmatizer.words

فقط به مالکیت معنوی فهرست واژه‌ها توجه داشته باشید. چون واژه‌ها از پروژه [ویراستیار](https://sourceforge.net/projects/virastyar/) اومدن و مسئول این پروژه شخصا به ما اجازه استفاده در هضم رو دادن.

**Comment by ahangarha** [comment]
خیلی ممنون

**Comment by ahangarha** [comment]
متاسفانه کدی که دادید کار نمی کنه
```
from hazm import stopwords
stopwords.words()
```
نتیجه
```
from hazm import stopwords
ImportError: cannot import name stopwords
```

**Comment by nournia** [comment]
شما باید نسخه در حال توسعه رو از روی گیت‌هاب نصب کنید:

   pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

**Comment by ahangarha** [comment]
<div dir='rtl' align='right'>
آیا دلیلی وجود داره که یک روش مشابه برای دسترسی به لیست کلمات و ایست‌واژه‌ها وجود نداره؟ به نظرتون ایرادی داره اگر یک متد داشت که به عنوان میان‌بر عمل کنه و این لیست‌ها به یک روش مشابه قابل دسترسی باشن؟
</div>

**Comment by nournia** [comment]
<div dir=rtl>

دو تابع `words_list` و `stopwords_list` برای دسترسی به فهرست واژه‌ها در نسخه در حال توسعه اضافه شدن و البته شکل قبلی دسترسی به stopwordها دیگه کار نمی‌کنه.

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
بنده نسخه جدید هضم رو نصب کردم ولی خطای زیر رو میده:
from hazm import stopwords
ImportError: cannot import name 'stopwords'
نسخه هضم موجود: Successfully installed hazm-0.5.3
با تشکر فراوان

**Comment by puraminy** [comment]
@MahdiDoost 
You can use
`hazm.stopwords_list()`

**Comment by Saramovahedi1996** [comment]
from hazm import Lemmatizer
lemmatizer = Lemmatizer(word1)
print(lemmatizer)
سلام من متنم رو word tokenize  
کردم و توی ورد 1 ذخیره کردم 
حالا با این دستور نمیتونم لیمیتیزرش کنم میشه راهنمایی کنین؟

**Comment by Saramovahedi1996** [comment]
from hazm import  sent_tokenize
hazm.stopwords_list()
print(sent_tokenize(text))
from hazm import  word_tokenize
word1=word_tokenize(text)
print(word1)
[w for w in word1 if w not in stopwords_list()]
print(stopwords_list(word1))
همچنین این کد رو نوشتم که استاپ ورد هارو حذف کنم ولی کار نمیکنه کدم

**Comment by Saramovahedi1996** [comment]
یه سوال دیگه هم داشتم 
این که آیا در هضم امکانی مثل ورد نت وجود داره؟
wordnet*
