### ISSUE TITLE
replacing 'coding utf8' with more known 'coding utf-8'

### ISSUE THREAD

**Issue by AurangZ** [sobhe/hazm#79]
In order to use the library in Django coding utf8 on top of the file returns with the following error, if you can replace utf8 with utf-8, then it will fix the issue.

xgettext: ./lib/python2.7/site-packages/hazm/Chunker.py:1: Unknown encoding "utf8". Proceeding with ASCII instead.
xgettext: Non-ASCII string at ./lib/python2.7/site-packages/hazm/Chunker.py:29.
          Please specify the source encoding through --from-code or through a comment
          as specified in http://www.python.org/peps/pep-0263.html.

**Comment by AurangZ** [comment]
Thanks.

**Comment by nournia** [comment]
<div dir=rtl>
انجام شد.
