### ISSUE TITLE
مشکل استفاده از پوشه مدل‌ها

### ISSUE THREAD

**Issue by Ahmadzadeh920** [sobhe/hazm#81]
با سلام 
من python 2.7 را نصب کردم با  hazm=0.4 اما در هنگام استفاده 
tagger = POSTagger()
با خطا 
LookupError: Could not find stanford-postagger.jar jar file at resources/stanford-postagger.jar
مواجه می شوم لطفا راهنمایی فرمایید

**Comment by nournia** [comment]
<div dir=rtl>
مشکل این هست که محتوی پوشه resources کنار پروژه قرار داده نشده.

توصیه می‌کنم برای استفاده از نسخه جدید هضم، بخش نصب رو در [سایت هضم](http://www.sobhe.ir/hazm/) نگاه بندازید، راهنمایی برای نصب روی ویندوز نوشته شده.

**Comment by Ahmadzadeh920** [comment]
با سلام .
من فقظ موفق به نصب hazm ورژن 0,4 شده ام حال فایل resource را از آدرس زیر
دانلود کردم :
https://github.com/sobhe/hazm/releases/download/v0.4/resources-0.4.zip
حال چگونه آنرا با aconda نصب کنم : چه دستوری باید نوشته شود؟
فایل resource در چه جایی باید قرار گیرد؟
با تشکر
احمدزاده

2016-12-18 7:53 GMT-08:00 Alireza Nourian <notifications@github.com>:

**Comment by Ahmadzadeh920** [comment]
سلام اقای مهندس
لطفا مرا راهنمایی فرمایید برای کار پژوهشی کارشناسی ارشد مورد نیازم است.
با تشکر احمدزاده

**Comment by nournia** [comment]
<div dir=rtl>
لطفا این فایل رو کنار پروژه‌تون اکسترکت کنید و محتوی‌ش رو در پوشه resources قرار بدید.

با آناکوندا هم مشکلی نیست.

**Comment by Ahmadzadeh920** [comment]
*با تشکر از راهنمایی شما*
*موفق باشید*

2016-12-19 7:38 GMT-08:00 Alireza Nourian <notifications@github.com>:
