### ISSUE TITLE
stop word

### ISSUE THREAD

**Issue by barooni69** [sobhe/hazm#85]
سلام
ببخشید هضم لیست کلمات توقف را داره؟

**Comment by ahangarha** [comment]
سلام بله داره. با یک جستجوی کوچک می‌تونید پیداش کنید.

**Comment by nournia** [comment]
<div dir=rtl>

برای استفاده از این لیست باید هضم رو از سورس نصب کنید:


    sudo pip install https://github.com/sobhe/hazm/archive/master.zip --upgrade

چون هنوز در بسته منتشر شده این ویژگی رو قرار ندادیم.

**Comment by barooni69** [comment]
تشکر مهندس
خدا قوت
