### ISSUE TITLE
Problem in SentenceTokenizer

### ISSUE THREAD

**Issue by blackunx** [sobhe/hazm#86]
It doesn't split sentences from " ؛ " character.

**Comment by nournia** [comment]
<div dir=rtl>

در زبان انگلیسی ظاهرا جمله‌ها رو با نقطه ویرگول جدا نمی‌کنن، مثلا در [این صفحه](http://nlp.stanford.edu:8080/parser/index.jsp) می‌تونید تست کنید.

اینکه در فارسی چه کار کنیم، باید بررسی بشه.

**Comment by nournia** [comment]
<div dir=rtl>

با آقای رسولی @rasoolims هم در این زمینه مشورت کردم و نظر ایشون این بود که نباید جمله رو با نقطه‌ویرگول تقطیع کرد.
