### ISSUE TITLE
لینک درست دسترسی به پیکره همشهری

### ISSUE THREAD

**Issue by ahangarha** [sobhe/hazm#89]
<div dir='rtl'>
سلام<br>
<br>
به دنبال پیکره‌ی همشهری بودم که به لینکی که در HamshahriReader.py بود رسیدم. به نظر می‌رسه که لینک مورد نظر دیگر در دسترس نیست و باید این لینک با لینک جدید جایگزین شود.
</div>

[HamshahriReader.py](https://github.com/sobhe/hazm/blob/master/hazm/HamshahriReader.py)
[لینک فعلی کار نمی‌کند](http://ece.ut.ac.ir/dbrg/hamshahri/files/HAM2/Corpus.zip)
[لینک جدید در این صفحه است](http://dbrg.ut.ac.ir/Hamshahri/download.html#version2)

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لینک اصلاح شد.
خیلی ممنون

**Comment by samanehmirzaei** [comment]
با سلام لطفا لینک جدید پیکره همشهری را بگذارید متاسفانه دو لینک در دسترس خراب هستند و دسترسی نمیشه پیدا کرد. با تشکر.

**Comment by ahangarha** [comment]
@samanehmirzaei پیوندهای جدیدی دارید؟

**Comment by samanehmirzaei** [comment]
> @samanehmirzaei پیوندهای جدیدی دارید؟

 من ندارم. چون دسترسی به این پیکره رو نیاز داشتم لینک هایی که گذاشتید متاسفانه کار نکرد ازتون خواستم دوباره جدیدش رو اگر شما دسترسی دارید، بزارید؟
