### ISSUE TITLE
یک مشکل کوچک در تشخیص جمله ها

### ISSUE THREAD

**Issue by kharazi** [sobhe/hazm#9]
سلام
Sentence_tokenizer 
چیزهایی شبیه این را از نقطه جمله تشخیص می دهد. نمی دانم چطوری باید تشخیص داد که این ها جمله نیستند.

```
     آقای نامردی به نام "میم.الف" که عضو کا.گ.ب است به شرکت ج.ا حمله کرد و دی.ان.ای وحید را دزدید و آن را روی سایت
googol.com قرار داد. 
```

**Comment by kokabi1365** [comment]
این مشکل تا حد خوبی الان حل شده.
