### ISSUE TITLE
ریشه یابی افعال

### ISSUE THREAD

**Issue by NimaKhatir** [sobhe/hazm#90]
سلام روزتون بخیر

اگه بخوام کلمات را در یک متن فارسی ریشه یابی کنم باید چیکار کنم؟ تابع لماتایزر هضم خوبه فقط افعال منفی رو به ریشه مثبت میبره میخوام منفی بمونه یعنی به ریشه ببره اما بگه که این فعل منفیه نه مثبت

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خب ریشه فعل منفی با فعل مثبت فرقی نداره.

برای حل این مشکل توصیه می‌کنم چک کنید اگر اول فعل «ن» داشت، بگید منفیه. ممکنه استثناهایی باشن که شامل این قاعده نشن، ولی خب قابل چشم‌پوشی هستن.

**Comment by NimaKhatir** [comment]
اخه برای انالیزاحساسی یا کارهای تحلیلی نیاز است که بفهمیم فعل مثبت است یا منفی
برای کار من که مقایسه متن هاست جمله "بچه ها بازی کردن دوست دارند" و جمله "بچه ها بازی کردن دوست ندارد" را یکسان میگیرد اما غیر این است 
برخی ابزار ریشه یابی دانشگاه فردوسی منفی رو لحاظ میکنه اما زبانش پایتون نیس

**Comment by nournia** [comment]
<div dir=rtl>
این راهی که پیشنهاد کردم خوب نبود؟

**Comment by NimaKhatir** [comment]
خوب که هس خواستم راه بی دردسرتر پیدا کنم

**Comment by MahdiDoost** [comment]
بسم الله الرحمن الرحیم
با سلام
lemmatizer ,stemmer  هر کدام از توابع 
برای چه مواردی مناسب هستند؟
با سپاس فراوان

**Comment by nournia** [comment]
<div dir=rtl>

سلام
اون چیزی که شما به عنوان ریشه‌یاب انتظار دارید همون lemmatizer هست و ابزار stemmer بخش‌هایی از کلمه رو حذف می‌کنه تا به یک شکل عام از کلمه برسه. می‌شه گفت یک ایده قدیمی هست و برای افزایش سرعت ازش استفاده می‌شه.
