### ISSUE TITLE
اضافه کردن پیکره جدید

### ISSUE THREAD

**Issue by zshayesteh** [sobhe/hazm#91]
با سلام و تشکر از تهیه کنندگان پروژه متن بازی که در اختیار بقیه هم قرار گرفته.
راستش من زبان پایتون بلد نیستم ولی برای پایان نامم و با توجه به برنامه شما باید یادش بگیرم.اما در همین مراحل اولیه سوالی داشتم که 1. آیا میشه پیکره جدیدی رو به پیکره های این برنامه اضافه کرد و 2. آیا غیر از کدنویسی کار دیگه ای هم برای این منظور لازمه انجام بدیم یا خیر؟
3. همین اضافه کردن پیکره جدید در نسخه سی شارپ برنامه هم امکان پذیره؟
4. نسخه سی شارپ همه امکانات نسخه پایتون رو داره یا نه بعضی از ابزارها رو نداره؟

با تشکر

**Comment by nournia** [comment]
<div dir=rtl>

سلام
ما برای پیکره‌های مختلف واسطی رو آماده کردیم که استفاده از اونها رو آسون بکنیم ولی شما برای استفاده از پیکره‌های دیگه نیازی به نوشتن واسط ندارید، خودتون مستقیم داده‌ها رو بخونید. البته اگر واسطش رو برای هضم هم بنویسید، خوشحال می‌شیم. اگر اسم پیکره رو هم بگید، شاید خودمون براش واسط نوشتیم.
باید کد بنویسید دیگه، کار دیگه‌ای نیست.

نسخه سی‌شارپ هضم رو دوست دیگری توسعه دادن و برای این سوال باید با خودشون صحبت کنید. نسخه سی‌شارپ تبدیل شده بعضی از بخش‌های نسخه قدیمی هضم هست.

**Comment by zshayesteh** [comment]
سلام
پیکره مورد نظر من ابتدا پیکره پاسخ و سپس پرسیکا هست که پرسیکا مثکه موجود بود ولی پاسخ وجود نداشت. متشکر میشم اگر واسط پاسخ رو هم بذارید.اگر هم من بعد از یادگیری پایتون تونستم بنویسم حتما میذارم :)
با تشکر از شما
