### ISSUE TITLE
مشکل نصب در ویندوز

### ISSUE THREAD

**Issue by hamiGH** [sobhe/hazm#92]
pip install hazm دستور 
در ویندوز خطا می دهد.
من سایت رو هم بررسی کردم که نکته ای ننوشته بود
https://github.com/sobhe/hazm/issues/87

**Comment by ahangarha** [comment]
می‌شه مشخص کنید که دقیقا مراحل نصب‌تون چیه و چه خطایی دریافت می‌کنید؟

**Comment by nournia** [comment]
<div dir=rtl>

در سایت نوشته:

> برای نصب روی ویندوز، لازم است ویژگی [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) را فعال کرده و با اجرای دستور زیر، پایتون را برای نصب هضم آماده کنید:
> ...

**Comment by hamiGH** [comment]
:برای همه نسخه های ویندوز فعال نمیشه طبق لینک مورد نظر WSL ویژگی 
Prerequisites:
    -Your PC must be running a 64-bit version of Windows 10 Anniversary Update build 14393 or later


:اروری که من موقع نصب میگیرم به این صورته:

pip install hazm
Collecting hazm
  Using cached hazm-0.5.2-py2.py3-none-any.whl
Collecting libwapiti>=0.2.1 (from hazm)
  Using cached libwapiti-0.2.1.tar.gz
Collecting nltk==3.0.5 (from hazm)
  Using cached nltk-3.0.5.zip
Requirement already satisfied: six in c:\python27\lib\site-packages (from libwapiti>=0.2.1->hazm)
Installing collected packages: libwapiti, nltk, hazm
  Running setup.py install for libwapiti ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\HamiGH\\appdata\\local\\temp\\pip-build-loirqh\\libwapiti\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\HamiGH\appdata\local\temp\pip-otz1ka-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\wapiti
    copying wapiti\api.py -> build\lib.win-amd64-2.7\wapiti
    copying wapiti\script.py -> build\lib.win-amd64-2.7\wapiti
    copying wapiti\__init__.py -> build\lib.win-amd64-2.7\wapiti
    running egg_info
    writing requirements to libwapiti.egg-info\requires.txt
    writing libwapiti.egg-info\PKG-INFO
    writing top-level names to libwapiti.egg-info\top_level.txt
    writing dependency_links to libwapiti.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'libwapiti.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'libwapiti.egg-info\SOURCES.txt'
    running build_ext
    building 'libwapiti' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\cwapiti
    creating build\temp.win-amd64-2.7\Release\cwapiti\src
    creating build\temp.win-amd64-2.7\Release\libwapiti
    creating build\temp.win-amd64-2.7\Release\libwapiti\src
    C:\Users\HamiGH\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icwapiti/src -Ilibwapiti -Ic:\python27\include -Ic:\python27\PC /Tccwapiti/src/bcd.c /Fobuild\temp.win-amd64-2.7\Release\cwapiti/src/bcd.obj -std=c99
    cl : Command line warning D9002 : ignoring unknown option '-std=c99'
    bcd.c
    cwapiti/src/bcd.c(30) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
    error: command 'C:\\Users\\HamiGH\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by nournia** [comment]
<div dir=rtl>

نصب هضم روی ویندوز کار مشکلی هست و برای این منظور می‌تونید از `cygwin` استفاده کنید. اگرچه توصیه من این هست که نسخه جدید ویندوز رو نصب کنید که هضم رو خیلی آسون نصب می‌کنه.

**Comment by hamiGH** [comment]
خیلی ممنون بابت کتابخانه خوبتون  . من هضم رو تو لینوکس نصب کردم و ازش استفاده کردم و خیلی خوب بود و به بقیه هم توصیه میکنم همین کارو کنند
