### ISSUE TITLE
problem with persian.tagger

### ISSUE THREAD

**Issue by sadegh-khan** [sobhe/hazm#94]
with running test.py file i have some error:

`NLTK was unable to find the resources/persian.tagger file!
    Use software specific configuration paramaters or set the STANFORD_MODELS environment variable.`

`File "/home/sadegh-khan/Desktop/Hazm - NLTK/hazm-master/hazm-master/hazm/POSTagger.py", line 19, in hazm.POSTagger.StanfordPOSTagger
Failed example:
    tagger.tag(['من', 'به', 'مدرسه', 'رفته_بودم', '.'])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest hazm.POSTagger.StanfordPOSTagger[1]>", line 1, in <module>
        tagger.tag(['من', 'به', 'مدرسه', 'رفته_بودم', '.'])
    NameError: name 'tagger' is not defined`

**Comment by nournia** [comment]
<div dir=auto>

سلام
فکر می‌کنم شما باید مطابق توضیح سایت، پوشه resources رو کنار پروژه قرار بدید.
دستور دقیق اجرای تست‌ها هم اینجاست:
https://github.com/sobhe/hazm/blob/master/.travis.yml

**Comment by 3adegh** [comment]
<p dir='rtl' align='right'>سلام، سپاس مشکلم حل شد، فقط میخواستم بدونم چطور میتونم لیست pos tag های ممکن رو داشته باشم (همان لیست ارایه شده در  Penn Treebank Project هست یا فرق داره؟). همچنین چطور به لیستی از مخفف های استفاده شده برای Relation ها (برای مثال NVE) میتونم دسترسی داشته باشم
</p>

**Comment by nournia** [comment]
<div dir=rtl>

سلام
برچسب‌های تحلیل صرفی روی داده‌ها  «پیکره» آموزش دیدن:

    Bijankhan, M., Sheykhzadegan, J., Bahrani, M., & Ghayoomi, M. (2011). Lessons from building a Persian written corpus: Peykare. Language Resources and Evaluation, 45, 143–164.

و تجزیه‌گر نحوی هم روی «پیکره وابستگی نحوی زبان فارسی» آموزش دیده:

    M. S. Rasooli, M. Kouhestani, and A. Moloodi, “Development of a Persian Syntactic Dependency Treebank,” in Proceedings of NAACL-HLT, 2013, pp. 306–314.

در مقاله‌ها فهرست تگ‌ها به همراه توضیح‌شون اومده.

**Comment by mjmaher987** [comment]
سلام و وقت بخیر.
من در استفاده از این کتابخانه به مشکل برمیخورم.
موقع اجرای دستور tagger.tag ( word_tokenize( 'ما بسیار کتاب می‌خوانیم' )) مطابق با داکیومنتیشن سایت هضم، و همچنین نصب پیش نیازهای لازم در کولب، سشن کرش میکنه و این پیام نوشته میشه:
session crashed after...
و اطلاع خاصی هم نمیده.
