### ISSUE TITLE
What is the difference between ADJ & ADJe label in POS Tagging?

### ISSUE THREAD

**Issue by stejesh** [sobhe/hazm#95]
There are a number of labels generated by hazm,

what does an extra 'e' at the end of certain labels mean in this particular tagger??

in other words,
What is the difference between

ADJ & ADJe
N & Ne
ADV, ADVe
NUM, NUMe
PRO, PROe

etc etc

**Comment by nournia** [comment]
This `e` character indicates [ezafe diacritic](https://en.wikipedia.org/wiki/Ez%C4%81fe) that is hidden in Persian text and `hazm` finds it. If you don't need this information just ignore it and use ADJe as ADJ.

More information about ezafe usecase:

A. Nourian, M. S. Rasooli, M. Imany, and H. Faili, “On the Importance of Ezafe Construction in Persian Parsing,” in The 53rd Annual Meeting of the Association for Computational Linguistics (ACL) and the 7h International Joint Conference on Natural Language Processing (IJCNLP), 2015.
