### ISSUE TITLE
مشکل در ریشه‌یابی افعال

### ISSUE THREAD

**Issue by zeinabm** [sobhe/hazm#96]
اگر که ریشه‌یاب ریشه فعل را نداند -مانند فعل می‌لغزد یا یک فعل غلط مانند تبنشست- خود فعل را به عنوان ریشه برمی‌گرداند.
همچنین اگر فعل با ریشه آن یکسان باشد، مانند دید، شنید، گفت، رفت و ... در این حالت هم خود فعل به عنوان ریشه برگردانده می‌شود.
چگونه بین این دو حالت تمایز قائل شویم؟

**Comment by nournia** [comment]
<div dir=rtl>
این موردی که نوشتید، خطای نرم‌افزاری هست و باید رفع بشه. فکر کنم خوبه ریشه «رفت» رو هم «رفت#رو» بگذاریم. در هر حال این تفاوت که می‌گید باید وجود داشته باشه.

**Comment by zeinabm** [comment]
ممنون

2017-07-24 19:56 GMT+04:30 Alireza Nourian <notifications@github.com>:

**Comment by nournia** [comment]
<div dir=rtl>

این مشکل در نسخه در حال توسعه حل شد.
ممنون از شما.
