### ISSUE TITLE
پارسر معنایی

### ISSUE THREAD

**Issue by azarezade** [sobhe/hazm#97]
سلام
آیا هضم می‌تواند پارس معنایی هم انجام دهد؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
متاسفانه خیر.
در حال حاضر داده ارتباط معنایی واژه‌ها در فارسی منتشر نشده. البته آماده شده، ولی هنوز منتشر نشده.
به امید خدا وقتی این داده در دسترس عموم قرار بگیره، ما هم می‌گیریم و مدل تحلیل معنایی رو به هضم اضافه می‌کنیم.

**Comment by azarezade** [comment]
خیلی ممنون
 داده ارتباط معنایی که گفتید به چه فرمتی هست
یعنی مثلا یک جمله و درخت پارسش هست
یا اینکه داده‌هایی مثل ویکیپدیا یا فری‌بیس هست

**Comment by nournia** [comment]
<div dir=rtl>

همین داده‌های پیکره درخت وابستگی نحوی رو برچسب‌گذاری معنای کردن.
که الان مدت‌هاست آماده شده ولی منتشر نشده.

**Comment by azarezade** [comment]
بله،‌ممنون.
شما از هم از روش 
CCG
که در
nltk
استفاده شده برای پارس معنایی استفاده میکنید؟

**Comment by nournia** [comment]
<div dir=rtl>

هضم در حال حاضر تحلیل معنایی انجام نمی‌ده.
وقتی بخوایم این ویژگی رو اضافه کنیم در مورد نحوه انجام این کار تصمیم می‌گیریم.
الان نمی‌دونم جواب سوال شما رو.
